// Command genblocks generates internal/world/blocks_gen.go from
// minecraft-data's blocks.json (1.21.8).
//
// Usage:
//
//	go run ./cmd/genblocks
//
// The output is a Go map DefaultStateByName[string]Block for lookups by
// block name (e.g., "dirt" -> 10) and DefaultStateByBlockID[int32]Block
// for lookups by base block ID (e.g., 9 -> 10 for dirt).
//
// Idempotent: regenerate any time minecraft-data updates.
package main

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"sort"
)

type block struct {
	ID           int32  `json:"id"`
	Name         string `json:"name"`
	DefaultState uint16 `json:"defaultState"`
}

type item struct {
	ID   int32  `json:"id"`
	Name string `json:"name"`
}

func readBlocks(path string) ([]block, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, err
	}
	var blocks []block
	if err := json.Unmarshal(data, &blocks); err != nil {
		return nil, err
	}

	// Sort by name for stable diffs across regenerations.
	sort.Slice(blocks, func(i, j int) bool {
		return blocks[i].Name < blocks[j].Name
	})

	// Deduplicate by name (defensive: JSON shouldn't have dups, but be safe).
	seen := make(map[string]bool, len(blocks))
	unique := make([]block, 0, len(blocks))
	for _, b := range blocks {
		if seen[b.Name] {
			continue
		}
		seen[b.Name] = true
		unique = append(unique, b)
	}
	return unique, nil
}

func readItems(path string) ([]item, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, err
	}
	var items []item
	if err := json.Unmarshal(data, &items); err != nil {
		return nil, err
	}
	sort.Slice(items, func(i, j int) bool { return items[i].ID < items[j].ID })
	return items, nil
}

// countItemBlockMatches returns the number of items that have a matching block
// (by name). Used for the generator's progress log.
func countItemBlockMatches(items []item, blocks []block) int {
	nameToBlock := make(map[string]block, len(blocks))
	for _, b := range blocks {
		nameToBlock[b.Name] = b
	}
	n := 0
	for _, it := range items {
		if _, ok := nameToBlock[it.Name]; ok {
			n++
		}
	}
	return n
}

func main() {
	blocksIn := filepath.Join("node_modules", "minecraft-data", "minecraft-data",
		"data", "pc", "1.21.8", "blocks.json")
	itemsIn := filepath.Join("node_modules", "minecraft-data", "minecraft-data",
		"data", "pc", "1.21.8", "items.json")
	out := filepath.Join("internal", "world", "blocks_gen.go")

	blocks, err := readBlocks(blocksIn)
	if err != nil {
		fmt.Fprintf(os.Stderr, "read blocks: %v\n", err)
		fmt.Fprintf(os.Stderr, "Hint: run `npm install` in the project root first.\n")
		os.Exit(1)
	}

	items, err := readItems(itemsIn)
	if err != nil {
		fmt.Fprintf(os.Stderr, "read items: %v\n", err)
		os.Exit(1)
	}

	if err := writeGen(out, blocks, items); err != nil {
		fmt.Fprintf(os.Stderr, "write %s: %v\n", out, err)
		os.Exit(1)
	}

	fmt.Printf("Generated %s: %d block entries, %d item->block mappings\n",
		out, len(blocks), countItemBlockMatches(items, blocks))
}

func writeGen(path string, blocks []block, items []item) error {
	// Build name->state lookup for resolving item->block.
	nameToState := make(map[string]uint16, len(blocks))
	for _, blk := range blocks {
		nameToState[blk.Name] = blk.DefaultState
	}

	var b []byte
	b = append(b, "// Code generated by cmd/genblocks. DO NOT EDIT.\n"...)
	b = append(b, "// Source: node_modules/minecraft-data/minecraft-data/data/pc/1.21.8/blocks.json\n"...)
	b = append(b, "//                   node_modules/minecraft-data/minecraft-data/data/pc/1.21.8/items.json\n"...)
	b = append(b, "//\n"...)
	b = append(b, "// Regenerate with: go run ./cmd/genblocks\n"...)
	b = append(b, "\n"...)
	b = append(b, "package world\n\n"...)
	b = append(b, "// DefaultStateByName returns the default block state ID for a given block name.\n"...)
	b = append(b, "// The map covers all base block types defined in minecraft-data 1.21.8\n"...)
	b = append(b, "// (e.g., \"dirt\" -> 10). State IDs are the protocol wire IDs used in chunks.\n"...)
	b = append(b, fmt.Sprintf("var DefaultStateByName = map[string]Block{\n")...)

	for _, blk := range blocks {
		// name is ASCII so no escaping needed; defaultState is uint16 < 65536.
		b = append(b, fmt.Sprintf("\t%q: %d,\n", blk.Name, blk.DefaultState)...)
	}
	b = append(b, "}\n\n"...)

	b = append(b, "// DefaultStateByBlockID returns the default state ID for a given base block\n"...)
	b = append(b, "// registry ID (the `id` field in blocks.json, NOT the same as the state ID).\n"...)
	b = append(b, "// Useful for mapping item IDs to block states, since some items and blocks\n"...)
	b = append(b, "// share the same numeric ID space (e.g., dirt item id=28, dirt block id=9).\n"...)
	b = append(b, fmt.Sprintf("var DefaultStateByBlockID = map[int32]Block{\n")...)
	for _, blk := range blocks {
		b = append(b, fmt.Sprintf("\t%d: %d, // %s\n", blk.ID, blk.DefaultState, blk.Name)...)
	}
	b = append(b, "}\n\n"...)

	b = append(b, "// ItemIDToBlockState maps an item registry ID to its corresponding block default\n"...)
	b = append(b, "// state ID, if the item represents a placeable block. Built by joining\n"...)
	b = append(b, "// items.json (item id -> item name) with blocks.json (name -> default state).\n"...)
	b = append(b, "// Lookups are O(1) and used by Player.placeBlock() to resolve what block to\n"...)
	b = append(b, "// place when a player right-clicks (use_item_on) with an item in hand.\n"...)
	b = append(b, fmt.Sprintf("var ItemIDToBlockState = map[int32]Block{\n")...)
	for _, it := range items {
		if state, ok := nameToState[it.Name]; ok {
			b = append(b, fmt.Sprintf("\t%d: %d, // %s\n", it.ID, state, it.Name)...)
		}
	}
	b = append(b, "}\n"...)

	return os.WriteFile(path, b, 0o644)
}
