// Code generated by cmd/genblocks. DO NOT EDIT.
// Source: node_modules/minecraft-data/minecraft-data/data/pc/1.21.8/blocks.json
//                   node_modules/minecraft-data/minecraft-data/data/pc/1.21.8/items.json
//
// Regenerate with: go run ./cmd/genblocks

package world

// DefaultStateByName returns the default block state ID for a given block name.
// The map covers all base block types defined in minecraft-data 1.21.8
// (e.g., "dirt" -> 10). State IDs are the protocol wire IDs used in chunks.
var DefaultStateByName = map[string]Block{
	"acacia_button": 9501,
	"acacia_door": 12984,
	"acacia_fence": 12620,
	"acacia_fence_gate": 12308,
	"acacia_hanging_sign": 5163,
	"acacia_leaves": 391,
	"acacia_log": 149,
	"acacia_planks": 19,
	"acacia_pressure_plate": 5901,
	"acacia_sapling": 37,
	"acacia_sign": 4463,
	"acacia_slab": 12078,
	"acacia_stairs": 10704,
	"acacia_trapdoor": 6411,
	"acacia_wall_hanging_sign": 5731,
	"acacia_wall_sign": 4883,
	"acacia_wood": 214,
	"activator_rail": 10142,
	"air": 0,
	"allium": 2125,
	"amethyst_block": 22091,
	"amethyst_cluster": 22102,
	"ancient_debris": 20508,
	"andesite": 6,
	"andesite_slab": 15194,
	"andesite_stairs": 14828,
	"andesite_wall": 17810,
	"anvil": 9916,
	"attached_melon_stem": 7060,
	"attached_pumpkin_stem": 7056,
	"azalea": 25884,
	"azalea_leaves": 531,
	"azure_bluet": 2126,
	"bamboo": 14000,
	"bamboo_block": 169,
	"bamboo_button": 9621,
	"bamboo_door": 13304,
	"bamboo_fence": 12780,
	"bamboo_fence_gate": 12468,
	"bamboo_hanging_sign": 5675,
	"bamboo_mosaic": 28,
	"bamboo_mosaic_slab": 12114,
	"bamboo_mosaic_stairs": 11184,
	"bamboo_planks": 27,
	"bamboo_pressure_plate": 5911,
	"bamboo_sapling": 13999,
	"bamboo_sign": 4655,
	"bamboo_slab": 12108,
	"bamboo_stairs": 11104,
	"bamboo_trapdoor": 6731,
	"bamboo_wall_hanging_sign": 5795,
	"bamboo_wall_sign": 4931,
	"barrel": 19464,
	"barrier": 11255,
	"basalt": 6032,
	"beacon": 8702,
	"bedrock": 85,
	"bee_nest": 20457,
	"beehive": 20481,
	"beetroots": 13532,
	"bell": 19527,
	"big_dripleaf": 25937,
	"big_dripleaf_stem": 25969,
	"birch_button": 9453,
	"birch_door": 12856,
	"birch_fence": 12556,
	"birch_fence_gate": 12244,
	"birch_hanging_sign": 5099,
	"birch_leaves": 335,
	"birch_log": 143,
	"birch_planks": 17,
	"birch_pressure_plate": 5897,
	"birch_sapling": 33,
	"birch_sign": 4431,
	"birch_slab": 12066,
	"birch_stairs": 8541,
	"birch_trapdoor": 6283,
	"birch_wall_hanging_sign": 5723,
	"birch_wall_sign": 4875,
	"birch_wood": 208,
	"black_banner": 11888,
	"black_bed": 1974,
	"black_candle": 22044,
	"black_candle_cake": 22090,
	"black_carpet": 11632,
	"black_concrete": 13766,
	"black_concrete_powder": 13782,
	"black_glazed_terracotta": 13747,
	"black_shulker_box": 13685,
	"black_stained_glass": 6139,
	"black_stained_glass_pane": 10692,
	"black_terracotta": 10180,
	"black_wall_banner": 11964,
	"black_wool": 2108,
	"blackstone": 20520,
	"blackstone_slab": 20928,
	"blackstone_stairs": 20532,
	"blackstone_wall": 20604,
	"blast_furnace": 19484,
	"blue_banner": 11824,
	"blue_bed": 1910,
	"blue_candle": 21980,
	"blue_candle_cake": 22082,
	"blue_carpet": 11628,
	"blue_concrete": 13762,
	"blue_concrete_powder": 13778,
	"blue_glazed_terracotta": 13731,
	"blue_ice": 13996,
	"blue_orchid": 2124,
	"blue_shulker_box": 13661,
	"blue_stained_glass": 6135,
	"blue_stained_glass_pane": 10564,
	"blue_terracotta": 10176,
	"blue_wall_banner": 11948,
	"blue_wool": 2104,
	"bone_block": 13570,
	"bookshelf": 2142,
	"brain_coral": 13880,
	"brain_coral_block": 13864,
	"brain_coral_fan": 13900,
	"brain_coral_wall_fan": 13956,
	"brewing_stand": 8181,
	"brick_slab": 12156,
	"brick_stairs": 7411,
	"brick_wall": 15218,
	"bricks": 2139,
	"brown_banner": 11840,
	"brown_bed": 1926,
	"brown_candle": 21996,
	"brown_candle_cake": 22084,
	"brown_carpet": 11629,
	"brown_concrete": 13763,
	"brown_concrete_powder": 13779,
	"brown_glazed_terracotta": 13735,
	"brown_mushroom": 2135,
	"brown_mushroom_block": 6792,
	"brown_shulker_box": 13667,
	"brown_stained_glass": 6136,
	"brown_stained_glass_pane": 10596,
	"brown_terracotta": 10177,
	"brown_wall_banner": 11952,
	"brown_wool": 2105,
	"bubble_column": 14015,
	"bubble_coral": 13882,
	"bubble_coral_block": 13865,
	"bubble_coral_fan": 13902,
	"bubble_coral_wall_fan": 13964,
	"budding_amethyst": 22092,
	"bush": 2051,
	"cactus": 5960,
	"cactus_flower": 5976,
	"cake": 6053,
	"calcite": 23376,
	"calibrated_sculk_sensor": 23476,
	"campfire": 19569,
	"candle": 21788,
	"candle_cake": 22058,
	"carrots": 9380,
	"cartography_table": 19491,
	"carved_pumpkin": 6045,
	"cauldron": 8182,
	"cave_air": 14014,
	"cave_vines": 25830,
	"cave_vines_plant": 25882,
	"chain": 7019,
	"chain_command_block": 13556,
	"cherry_button": 9525,
	"cherry_door": 13048,
	"cherry_fence": 12652,
	"cherry_fence_gate": 12340,
	"cherry_hanging_sign": 5227,
	"cherry_leaves": 419,
	"cherry_log": 152,
	"cherry_planks": 20,
	"cherry_pressure_plate": 5903,
	"cherry_sapling": 39,
	"cherry_sign": 4495,
	"cherry_slab": 12084,
	"cherry_stairs": 10784,
	"cherry_trapdoor": 6475,
	"cherry_wall_hanging_sign": 5739,
	"cherry_wall_sign": 4891,
	"cherry_wood": 217,
	"chest": 3019,
	"chipped_anvil": 9920,
	"chiseled_bookshelf": 2206,
	"chiseled_copper": 24011,
	"chiseled_deepslate": 27643,
	"chiseled_nether_bricks": 21782,
	"chiseled_polished_blackstone": 20934,
	"chiseled_quartz_block": 10045,
	"chiseled_red_sandstone": 11969,
	"chiseled_resin_bricks": 8055,
	"chiseled_sandstone": 579,
	"chiseled_stone_bricks": 6783,
	"chiseled_tuff": 22963,
	"chiseled_tuff_bricks": 23375,
	"chorus_flower": 13427,
	"chorus_plant": 13426,
	"clay": 5977,
	"closed_eyeblossom": 27942,
	"coal_block": 11634,
	"coal_ore": 133,
	"coarse_dirt": 11,
	"cobbled_deepslate": 25999,
	"cobbled_deepslate_slab": 26083,
	"cobbled_deepslate_stairs": 26011,
	"cobbled_deepslate_wall": 26089,
	"cobblestone": 14,
	"cobblestone_slab": 12150,
	"cobblestone_stairs": 4789,
	"cobblestone_wall": 8706,
	"cobweb": 2047,
	"cocoa": 8203,
	"command_block": 8696,
	"comparator": 9985,
	"composter": 20432,
	"conduit": 13997,
	"copper_block": 23998,
	"copper_bulb": 25755,
	"copper_door": 24723,
	"copper_grate": 25737,
	"copper_ore": 24002,
	"copper_trapdoor": 25239,
	"cornflower": 2132,
	"cracked_deepslate_bricks": 27644,
	"cracked_deepslate_tiles": 27645,
	"cracked_nether_bricks": 21783,
	"cracked_polished_blackstone_bricks": 20933,
	"cracked_stone_bricks": 6782,
	"crafter": 27727,
	"crafting_table": 4341,
	"creaking_heart": 2927,
	"creeper_head": 9812,
	"creeper_wall_head": 9829,
	"crimson_button": 20164,
	"crimson_door": 20214,
	"crimson_fence": 19770,
	"crimson_fence_gate": 19938,
	"crimson_fungus": 19664,
	"crimson_hanging_sign": 5483,
	"crimson_hyphae": 19658,
	"crimson_nylium": 19663,
	"crimson_planks": 19721,
	"crimson_pressure_plate": 19736,
	"crimson_roots": 19720,
	"crimson_sign": 20332,
	"crimson_slab": 19726,
	"crimson_stairs": 20006,
	"crimson_stem": 19652,
	"crimson_trapdoor": 19818,
	"crimson_wall_hanging_sign": 5779,
	"crimson_wall_sign": 20396,
	"crying_obsidian": 20509,
	"cut_copper": 24007,
	"cut_copper_slab": 24357,
	"cut_copper_stairs": 24267,
	"cut_red_sandstone": 11970,
	"cut_red_sandstone_slab": 12192,
	"cut_sandstone": 580,
	"cut_sandstone_slab": 12138,
	"cyan_banner": 11792,
	"cyan_bed": 1878,
	"cyan_candle": 21948,
	"cyan_candle_cake": 22078,
	"cyan_carpet": 11626,
	"cyan_concrete": 13760,
	"cyan_concrete_powder": 13776,
	"cyan_glazed_terracotta": 13723,
	"cyan_shulker_box": 13649,
	"cyan_stained_glass": 6133,
	"cyan_stained_glass_pane": 10500,
	"cyan_terracotta": 10174,
	"cyan_wall_banner": 11940,
	"cyan_wool": 2102,
	"damaged_anvil": 9924,
	"dandelion": 2121,
	"dark_oak_button": 9549,
	"dark_oak_door": 13112,
	"dark_oak_fence": 12684,
	"dark_oak_fence_gate": 12372,
	"dark_oak_hanging_sign": 5355,
	"dark_oak_leaves": 447,
	"dark_oak_log": 155,
	"dark_oak_planks": 21,
	"dark_oak_pressure_plate": 5905,
	"dark_oak_sapling": 41,
	"dark_oak_sign": 4559,
	"dark_oak_slab": 12090,
	"dark_oak_stairs": 10864,
	"dark_oak_trapdoor": 6539,
	"dark_oak_wall_hanging_sign": 5755,
	"dark_oak_wall_sign": 4907,
	"dark_oak_wood": 220,
	"dark_prismarine": 11354,
	"dark_prismarine_slab": 11610,
	"dark_prismarine_stairs": 11526,
	"daylight_detector": 10016,
	"dead_brain_coral": 13870,
	"dead_brain_coral_block": 13859,
	"dead_brain_coral_fan": 13890,
	"dead_brain_coral_wall_fan": 13916,
	"dead_bubble_coral": 13872,
	"dead_bubble_coral_block": 13860,
	"dead_bubble_coral_fan": 13892,
	"dead_bubble_coral_wall_fan": 13924,
	"dead_bush": 2050,
	"dead_fire_coral": 13874,
	"dead_fire_coral_block": 13861,
	"dead_fire_coral_fan": 13894,
	"dead_fire_coral_wall_fan": 13932,
	"dead_horn_coral": 13876,
	"dead_horn_coral_block": 13862,
	"dead_horn_coral_fan": 13896,
	"dead_horn_coral_wall_fan": 13940,
	"dead_tube_coral": 13868,
	"dead_tube_coral_block": 13858,
	"dead_tube_coral_fan": 13888,
	"dead_tube_coral_wall_fan": 13908,
	"decorated_pot": 27675,
	"deepslate": 25997,
	"deepslate_brick_slab": 27316,
	"deepslate_brick_stairs": 27244,
	"deepslate_brick_wall": 27322,
	"deepslate_bricks": 27232,
	"deepslate_coal_ore": 134,
	"deepslate_copper_ore": 24003,
	"deepslate_diamond_ore": 4339,
	"deepslate_emerald_ore": 8296,
	"deepslate_gold_ore": 130,
	"deepslate_iron_ore": 132,
	"deepslate_lapis_ore": 564,
	"deepslate_redstone_ore": 5915,
	"deepslate_tile_slab": 26905,
	"deepslate_tile_stairs": 26833,
	"deepslate_tile_wall": 26911,
	"deepslate_tiles": 26821,
	"detector_rail": 2024,
	"diamond_block": 4340,
	"diamond_ore": 4338,
	"diorite": 4,
	"diorite_slab": 15212,
	"diorite_stairs": 15068,
	"diorite_wall": 19106,
	"dirt": 10,
	"dirt_path": 13536,
	"dispenser": 567,
	"dragon_egg": 8200,
	"dragon_head": 9852,
	"dragon_wall_head": 9869,
	"dried_ghast": 13827,
	"dried_kelp_block": 13810,
	"dripstone_block": 25828,
	"dropper": 10154,
	"emerald_block": 8449,
	"emerald_ore": 8295,
	"enchanting_table": 8173,
	"end_gateway": 13537,
	"end_portal": 8190,
	"end_portal_frame": 8195,
	"end_rod": 13361,
	"end_stone": 8199,
	"end_stone_brick_slab": 15170,
	"end_stone_brick_stairs": 14428,
	"end_stone_brick_wall": 18782,
	"end_stone_bricks": 13517,
	"ender_chest": 8298,
	"exposed_chiseled_copper": 24010,
	"exposed_copper": 23999,
	"exposed_copper_bulb": 25759,
	"exposed_copper_door": 24787,
	"exposed_copper_grate": 25739,
	"exposed_copper_trapdoor": 25303,
	"exposed_cut_copper": 24006,
	"exposed_cut_copper_slab": 24351,
	"exposed_cut_copper_stairs": 24187,
	"farmland": 4350,
	"fern": 2049,
	"fire": 2437,
	"fire_coral": 13884,
	"fire_coral_block": 13866,
	"fire_coral_fan": 13904,
	"fire_coral_wall_fan": 13972,
	"firefly_bush": 27945,
	"fletching_table": 19492,
	"flower_pot": 9351,
	"flowering_azalea": 25885,
	"flowering_azalea_leaves": 559,
	"frogspawn": 27664,
	"frosted_ice": 13562,
	"furnace": 4359,
	"gilded_blackstone": 21345,
	"glass": 562,
	"glass_pane": 7053,
	"glow_lichen": 7239,
	"glowstone": 6042,
	"gold_block": 2137,
	"gold_ore": 129,
	"granite": 2,
	"granite_slab": 15188,
	"granite_stairs": 14748,
	"granite_wall": 16514,
	"grass_block": 9,
	"gravel": 124,
	"gray_banner": 11760,
	"gray_bed": 1846,
	"gray_candle": 21916,
	"gray_candle_cake": 22074,
	"gray_carpet": 11624,
	"gray_concrete": 13758,
	"gray_concrete_powder": 13774,
	"gray_glazed_terracotta": 13715,
	"gray_shulker_box": 13637,
	"gray_stained_glass": 6131,
	"gray_stained_glass_pane": 10436,
	"gray_terracotta": 10172,
	"gray_wall_banner": 11932,
	"gray_wool": 2100,
	"green_banner": 11856,
	"green_bed": 1942,
	"green_candle": 22012,
	"green_candle_cake": 22086,
	"green_carpet": 11630,
	"green_concrete": 13764,
	"green_concrete_powder": 13780,
	"green_glazed_terracotta": 13739,
	"green_shulker_box": 13673,
	"green_stained_glass": 6137,
	"green_stained_glass_pane": 10628,
	"green_terracotta": 10178,
	"green_wall_banner": 11956,
	"green_wool": 2106,
	"grindstone": 19497,
	"hanging_roots": 25993,
	"hay_block": 11615,
	"heavy_core": 27775,
	"heavy_weighted_pressure_plate": 9968,
	"honey_block": 20505,
	"honeycomb_block": 20506,
	"hopper": 10034,
	"horn_coral": 13886,
	"horn_coral_block": 13867,
	"horn_coral_fan": 13906,
	"horn_coral_wall_fan": 13980,
	"ice": 5958,
	"infested_chiseled_stone_bricks": 6791,
	"infested_cobblestone": 6787,
	"infested_cracked_stone_bricks": 6790,
	"infested_deepslate": 27647,
	"infested_mossy_stone_bricks": 6789,
	"infested_stone": 6786,
	"infested_stone_bricks": 6788,
	"iron_bars": 7015,
	"iron_block": 2138,
	"iron_door": 5839,
	"iron_ore": 131,
	"iron_trapdoor": 11303,
	"jack_o_lantern": 6049,
	"jigsaw": 20425,
	"jukebox": 5995,
	"jungle_button": 9477,
	"jungle_door": 12920,
	"jungle_fence": 12588,
	"jungle_fence_gate": 12276,
	"jungle_hanging_sign": 5291,
	"jungle_leaves": 363,
	"jungle_log": 146,
	"jungle_planks": 18,
	"jungle_pressure_plate": 5899,
	"jungle_sapling": 35,
	"jungle_sign": 4527,
	"jungle_slab": 12072,
	"jungle_stairs": 8621,
	"jungle_trapdoor": 6347,
	"jungle_wall_hanging_sign": 5747,
	"jungle_wall_sign": 4899,
	"jungle_wood": 211,
	"kelp": 13783,
	"kelp_plant": 13809,
	"ladder": 4751,
	"lantern": 19561,
	"lapis_block": 565,
	"lapis_ore": 563,
	"large_amethyst_bud": 22114,
	"large_fern": 11647,
	"lava": 102,
	"lava_cauldron": 8186,
	"leaf_litter": 25919,
	"lectern": 19508,
	"lever": 5811,
	"light": 11287,
	"light_blue_banner": 11696,
	"light_blue_bed": 1782,
	"light_blue_candle": 21852,
	"light_blue_candle_cake": 22066,
	"light_blue_carpet": 11620,
	"light_blue_concrete": 13754,
	"light_blue_concrete_powder": 13770,
	"light_blue_glazed_terracotta": 13699,
	"light_blue_shulker_box": 13613,
	"light_blue_stained_glass": 6127,
	"light_blue_stained_glass_pane": 10308,
	"light_blue_terracotta": 10168,
	"light_blue_wall_banner": 11916,
	"light_blue_wool": 2096,
	"light_gray_banner": 11776,
	"light_gray_bed": 1862,
	"light_gray_candle": 21932,
	"light_gray_candle_cake": 22076,
	"light_gray_carpet": 11625,
	"light_gray_concrete": 13759,
	"light_gray_concrete_powder": 13775,
	"light_gray_glazed_terracotta": 13719,
	"light_gray_shulker_box": 13643,
	"light_gray_stained_glass": 6132,
	"light_gray_stained_glass_pane": 10468,
	"light_gray_terracotta": 10173,
	"light_gray_wall_banner": 11936,
	"light_gray_wool": 2101,
	"light_weighted_pressure_plate": 9952,
	"lightning_rod": 25803,
	"lilac": 11639,
	"lily_of_the_valley": 2134,
	"lily_pad": 7642,
	"lime_banner": 11728,
	"lime_bed": 1814,
	"lime_candle": 21884,
	"lime_candle_cake": 22070,
	"lime_carpet": 11622,
	"lime_concrete": 13756,
	"lime_concrete_powder": 13772,
	"lime_glazed_terracotta": 13707,
	"lime_shulker_box": 13625,
	"lime_stained_glass": 6129,
	"lime_stained_glass_pane": 10372,
	"lime_terracotta": 10170,
	"lime_wall_banner": 11924,
	"lime_wool": 2098,
	"lodestone": 20519,
	"loom": 19459,
	"magenta_banner": 11680,
	"magenta_bed": 1766,
	"magenta_candle": 21836,
	"magenta_candle_cake": 22064,
	"magenta_carpet": 11619,
	"magenta_concrete": 13753,
	"magenta_concrete_powder": 13769,
	"magenta_glazed_terracotta": 13695,
	"magenta_shulker_box": 13607,
	"magenta_stained_glass": 6126,
	"magenta_stained_glass_pane": 10276,
	"magenta_terracotta": 10167,
	"magenta_wall_banner": 11912,
	"magenta_wool": 2095,
	"magma_block": 13566,
	"mangrove_button": 9597,
	"mangrove_door": 13240,
	"mangrove_fence": 12748,
	"mangrove_fence_gate": 12436,
	"mangrove_hanging_sign": 5611,
	"mangrove_leaves": 503,
	"mangrove_log": 161,
	"mangrove_planks": 26,
	"mangrove_pressure_plate": 5909,
	"mangrove_propagule": 50,
	"mangrove_roots": 164,
	"mangrove_sign": 4623,
	"mangrove_slab": 12102,
	"mangrove_stairs": 11024,
	"mangrove_trapdoor": 6667,
	"mangrove_wall_hanging_sign": 5771,
	"mangrove_wall_sign": 4923,
	"mangrove_wood": 223,
	"medium_amethyst_bud": 22126,
	"melon": 7055,
	"melon_stem": 7072,
	"moss_block": 25935,
	"moss_carpet": 25886,
	"mossy_cobblestone": 2399,
	"mossy_cobblestone_slab": 15164,
	"mossy_cobblestone_stairs": 14348,
	"mossy_cobblestone_wall": 9030,
	"mossy_stone_brick_slab": 15152,
	"mossy_stone_brick_stairs": 14188,
	"mossy_stone_brick_wall": 16190,
	"mossy_stone_bricks": 6781,
	"moving_piston": 2109,
	"mud": 25995,
	"mud_brick_slab": 12168,
	"mud_brick_stairs": 7571,
	"mud_brick_wall": 17162,
	"mud_bricks": 6785,
	"muddy_mangrove_roots": 166,
	"mushroom_stem": 6920,
	"mycelium": 7641,
	"nether_brick_fence": 8088,
	"nether_brick_slab": 12174,
	"nether_brick_stairs": 8100,
	"nether_brick_wall": 17486,
	"nether_bricks": 8056,
	"nether_gold_ore": 135,
	"nether_portal": 6043,
	"nether_quartz_ore": 10033,
	"nether_sprouts": 19650,
	"nether_wart": 8169,
	"nether_wart_block": 13567,
	"netherite_block": 20507,
	"netherrack": 6028,
	"note_block": 582,
	"oak_button": 9405,
	"oak_door": 4697,
	"oak_fence": 6027,
	"oak_fence_gate": 7375,
	"oak_hanging_sign": 4971,
	"oak_leaves": 279,
	"oak_log": 137,
	"oak_planks": 15,
	"oak_pressure_plate": 5893,
	"oak_sapling": 29,
	"oak_sign": 4367,
	"oak_slab": 12054,
	"oak_stairs": 2949,
	"oak_trapdoor": 6155,
	"oak_wall_hanging_sign": 5707,
	"oak_wall_sign": 4859,
	"oak_wood": 202,
	"observer": 13578,
	"obsidian": 2400,
	"ochre_froglight": 27656,
	"open_eyeblossom": 27941,
	"orange_banner": 11664,
	"orange_bed": 1750,
	"orange_candle": 21820,
	"orange_candle_cake": 22062,
	"orange_carpet": 11618,
	"orange_concrete": 13752,
	"orange_concrete_powder": 13768,
	"orange_glazed_terracotta": 13691,
	"orange_shulker_box": 13601,
	"orange_stained_glass": 6125,
	"orange_stained_glass_pane": 10244,
	"orange_terracotta": 10166,
	"orange_tulip": 2128,
	"orange_wall_banner": 11908,
	"orange_wool": 2094,
	"oxeye_daisy": 2131,
	"oxidized_chiseled_copper": 24008,
	"oxidized_copper": 24001,
	"oxidized_copper_bulb": 25767,
	"oxidized_copper_door": 24851,
	"oxidized_copper_grate": 25743,
	"oxidized_copper_trapdoor": 25367,
	"oxidized_cut_copper": 24004,
	"oxidized_cut_copper_slab": 24339,
	"oxidized_cut_copper_stairs": 24027,
	"packed_ice": 11635,
	"packed_mud": 6784,
	"pale_hanging_moss": 27939,
	"pale_moss_block": 27776,
	"pale_moss_carpet": 27777,
	"pale_oak_button": 9573,
	"pale_oak_door": 13176,
	"pale_oak_fence": 12716,
	"pale_oak_fence_gate": 12404,
	"pale_oak_hanging_sign": 5419,
	"pale_oak_leaves": 475,
	"pale_oak_log": 158,
	"pale_oak_planks": 25,
	"pale_oak_pressure_plate": 5907,
	"pale_oak_sapling": 43,
	"pale_oak_sign": 4591,
	"pale_oak_slab": 12096,
	"pale_oak_stairs": 10944,
	"pale_oak_trapdoor": 6603,
	"pale_oak_wall_hanging_sign": 5763,
	"pale_oak_wall_sign": 4915,
	"pale_oak_wood": 23,
	"pearlescent_froglight": 27662,
	"peony": 11643,
	"petrified_oak_slab": 12144,
	"piglin_head": 9892,
	"piglin_wall_head": 9909,
	"pink_banner": 11744,
	"pink_bed": 1830,
	"pink_candle": 21900,
	"pink_candle_cake": 22072,
	"pink_carpet": 11623,
	"pink_concrete": 13757,
	"pink_concrete_powder": 13773,
	"pink_glazed_terracotta": 13711,
	"pink_petals": 25887,
	"pink_shulker_box": 13631,
	"pink_stained_glass": 6130,
	"pink_stained_glass_pane": 10404,
	"pink_terracotta": 10171,
	"pink_tulip": 2130,
	"pink_wall_banner": 11928,
	"pink_wool": 2099,
	"piston": 2063,
	"piston_head": 2071,
	"pitcher_crop": 13521,
	"pitcher_plant": 13531,
	"player_head": 9772,
	"player_wall_head": 9789,
	"podzol": 13,
	"pointed_dripstone": 25813,
	"polished_andesite": 7,
	"polished_andesite_slab": 15206,
	"polished_andesite_stairs": 14988,
	"polished_basalt": 6035,
	"polished_blackstone": 20931,
	"polished_blackstone_brick_slab": 20938,
	"polished_blackstone_brick_stairs": 20952,
	"polished_blackstone_brick_wall": 21024,
	"polished_blackstone_bricks": 20932,
	"polished_blackstone_button": 21443,
	"polished_blackstone_pressure_plate": 21433,
	"polished_blackstone_slab": 21429,
	"polished_blackstone_stairs": 21357,
	"polished_blackstone_wall": 21461,
	"polished_deepslate": 26410,
	"polished_deepslate_slab": 26494,
	"polished_deepslate_stairs": 26422,
	"polished_deepslate_wall": 26500,
	"polished_diorite": 5,
	"polished_diorite_slab": 15158,
	"polished_diorite_stairs": 14268,
	"polished_granite": 3,
	"polished_granite_slab": 15140,
	"polished_granite_stairs": 14028,
	"polished_tuff": 22552,
	"polished_tuff_slab": 22556,
	"polished_tuff_stairs": 22570,
	"polished_tuff_wall": 22642,
	"poppy": 2123,
	"potatoes": 9388,
	"potted_acacia_sapling": 9357,
	"potted_allium": 9366,
	"potted_azalea_bush": 27653,
	"potted_azure_bluet": 9367,
	"potted_bamboo": 14012,
	"potted_birch_sapling": 9355,
	"potted_blue_orchid": 9365,
	"potted_brown_mushroom": 9377,
	"potted_cactus": 9379,
	"potted_cherry_sapling": 9358,
	"potted_closed_eyeblossom": 27944,
	"potted_cornflower": 9373,
	"potted_crimson_fungus": 20515,
	"potted_crimson_roots": 20517,
	"potted_dandelion": 9363,
	"potted_dark_oak_sapling": 9359,
	"potted_dead_bush": 9378,
	"potted_fern": 9362,
	"potted_flowering_azalea_bush": 27654,
	"potted_jungle_sapling": 9356,
	"potted_lily_of_the_valley": 9374,
	"potted_mangrove_propagule": 9361,
	"potted_oak_sapling": 9353,
	"potted_open_eyeblossom": 27943,
	"potted_orange_tulip": 9369,
	"potted_oxeye_daisy": 9372,
	"potted_pale_oak_sapling": 9360,
	"potted_pink_tulip": 9371,
	"potted_poppy": 9364,
	"potted_red_mushroom": 9376,
	"potted_red_tulip": 9368,
	"potted_spruce_sapling": 9354,
	"potted_torchflower": 9352,
	"potted_warped_fungus": 20516,
	"potted_warped_roots": 20518,
	"potted_white_tulip": 9370,
	"potted_wither_rose": 9375,
	"powder_snow": 23378,
	"powder_snow_cauldron": 8187,
	"powered_rail": 2000,
	"prismarine": 11352,
	"prismarine_brick_slab": 11604,
	"prismarine_brick_stairs": 11446,
	"prismarine_bricks": 11353,
	"prismarine_slab": 11598,
	"prismarine_stairs": 11366,
	"prismarine_wall": 15542,
	"pumpkin": 7054,
	"pumpkin_stem": 7064,
	"purple_banner": 11808,
	"purple_bed": 1894,
	"purple_candle": 21964,
	"purple_candle_cake": 22080,
	"purple_carpet": 11627,
	"purple_concrete": 13761,
	"purple_concrete_powder": 13777,
	"purple_glazed_terracotta": 13727,
	"purple_shulker_box": 13655,
	"purple_stained_glass": 6134,
	"purple_stained_glass_pane": 10532,
	"purple_terracotta": 10175,
	"purple_wall_banner": 11944,
	"purple_wool": 2103,
	"purpur_block": 13433,
	"purpur_pillar": 13435,
	"purpur_slab": 12198,
	"purpur_stairs": 13448,
	"quartz_block": 10044,
	"quartz_bricks": 21784,
	"quartz_pillar": 10047,
	"quartz_slab": 12180,
	"quartz_stairs": 10060,
	"rail": 4759,
	"raw_copper_block": 27651,
	"raw_gold_block": 27652,
	"raw_iron_block": 27650,
	"red_banner": 11872,
	"red_bed": 1958,
	"red_candle": 22028,
	"red_candle_cake": 22088,
	"red_carpet": 11631,
	"red_concrete": 13765,
	"red_concrete_powder": 13781,
	"red_glazed_terracotta": 13743,
	"red_mushroom": 2136,
	"red_mushroom_block": 6856,
	"red_nether_brick_slab": 15200,
	"red_nether_brick_stairs": 14908,
	"red_nether_brick_wall": 18134,
	"red_nether_bricks": 13568,
	"red_sand": 123,
	"red_sandstone": 11968,
	"red_sandstone_slab": 12186,
	"red_sandstone_stairs": 11982,
	"red_sandstone_wall": 15866,
	"red_shulker_box": 13679,
	"red_stained_glass": 6138,
	"red_stained_glass_pane": 10660,
	"red_terracotta": 10179,
	"red_tulip": 2127,
	"red_wall_banner": 11960,
	"red_wool": 2107,
	"redstone_block": 10032,
	"redstone_lamp": 8202,
	"redstone_ore": 5913,
	"redstone_torch": 5916,
	"redstone_wall_torch": 5918,
	"redstone_wire": 4202,
	"reinforced_deepslate": 27665,
	"repeater": 6063,
	"repeating_command_block": 13544,
	"resin_block": 7643,
	"resin_brick_slab": 7728,
	"resin_brick_stairs": 7656,
	"resin_brick_wall": 7734,
	"resin_bricks": 7644,
	"resin_clump": 7367,
	"respawn_anchor": 20510,
	"rooted_dirt": 25994,
	"rose_bush": 11641,
	"sand": 118,
	"sandstone": 578,
	"sandstone_slab": 12132,
	"sandstone_stairs": 8226,
	"sandstone_wall": 18458,
	"scaffolding": 19458,
	"sculk": 23859,
	"sculk_catalyst": 23989,
	"sculk_sensor": 23380,
	"sculk_shrieker": 23997,
	"sculk_vein": 23987,
	"sea_lantern": 11613,
	"sea_pickle": 13988,
	"seagrass": 2054,
	"short_dry_grass": 2052,
	"short_grass": 2048,
	"shroomlight": 19665,
	"shulker_box": 13589,
	"skeleton_skull": 9652,
	"skeleton_wall_skull": 9669,
	"slime_block": 11253,
	"small_amethyst_bud": 22138,
	"small_dripleaf": 25979,
	"smithing_table": 19521,
	"smoker": 19476,
	"smooth_basalt": 27649,
	"smooth_quartz": 12203,
	"smooth_quartz_slab": 15182,
	"smooth_quartz_stairs": 14668,
	"smooth_red_sandstone": 12204,
	"smooth_red_sandstone_slab": 15146,
	"smooth_red_sandstone_stairs": 14108,
	"smooth_sandstone": 12202,
	"smooth_sandstone_slab": 15176,
	"smooth_sandstone_stairs": 14588,
	"smooth_stone": 12201,
	"smooth_stone_slab": 12126,
	"sniffer_egg": 13823,
	"snow": 5950,
	"snow_block": 5959,
	"soul_campfire": 19601,
	"soul_fire": 2918,
	"soul_lantern": 19565,
	"soul_sand": 6029,
	"soul_soil": 6030,
	"soul_torch": 6037,
	"soul_wall_torch": 6038,
	"spawner": 2919,
	"sponge": 560,
	"spore_blossom": 25883,
	"spruce_button": 9429,
	"spruce_door": 12792,
	"spruce_fence": 12524,
	"spruce_fence_gate": 12212,
	"spruce_hanging_sign": 5035,
	"spruce_leaves": 307,
	"spruce_log": 140,
	"spruce_planks": 16,
	"spruce_pressure_plate": 5895,
	"spruce_sapling": 31,
	"spruce_sign": 4399,
	"spruce_slab": 12060,
	"spruce_stairs": 8461,
	"spruce_trapdoor": 6219,
	"spruce_wall_hanging_sign": 5715,
	"spruce_wall_sign": 4867,
	"spruce_wood": 205,
	"sticky_piston": 2041,
	"stone": 1,
	"stone_brick_slab": 12162,
	"stone_brick_stairs": 7491,
	"stone_brick_wall": 16838,
	"stone_bricks": 6780,
	"stone_button": 5935,
	"stone_pressure_plate": 5827,
	"stone_slab": 12120,
	"stone_stairs": 14508,
	"stonecutter": 19522,
	"stripped_acacia_log": 181,
	"stripped_acacia_wood": 238,
	"stripped_bamboo_block": 199,
	"stripped_birch_log": 175,
	"stripped_birch_wood": 232,
	"stripped_cherry_log": 184,
	"stripped_cherry_wood": 241,
	"stripped_crimson_hyphae": 19661,
	"stripped_crimson_stem": 19655,
	"stripped_dark_oak_log": 187,
	"stripped_dark_oak_wood": 244,
	"stripped_jungle_log": 178,
	"stripped_jungle_wood": 235,
	"stripped_mangrove_log": 196,
	"stripped_mangrove_wood": 250,
	"stripped_oak_log": 193,
	"stripped_oak_wood": 226,
	"stripped_pale_oak_log": 190,
	"stripped_pale_oak_wood": 247,
	"stripped_spruce_log": 172,
	"stripped_spruce_wood": 229,
	"stripped_warped_hyphae": 19644,
	"stripped_warped_stem": 19638,
	"structure_block": 20412,
	"structure_void": 13572,
	"sugar_cane": 5978,
	"sunflower": 11637,
	"suspicious_gravel": 125,
	"suspicious_sand": 119,
	"sweet_berry_bush": 19630,
	"tall_dry_grass": 2053,
	"tall_grass": 11645,
	"tall_seagrass": 2056,
	"target": 20441,
	"terracotta": 11633,
	"test_block": 20427,
	"test_instance_block": 20431,
	"tinted_glass": 23377,
	"tnt": 2141,
	"torch": 2401,
	"torchflower": 2122,
	"torchflower_crop": 13518,
	"trapped_chest": 9929,
	"trial_spawner": 27736,
	"tripwire": 8448,
	"tripwire_hook": 8314,
	"tube_coral": 13878,
	"tube_coral_block": 13863,
	"tube_coral_fan": 13898,
	"tube_coral_wall_fan": 13948,
	"tuff": 22141,
	"tuff_brick_slab": 22968,
	"tuff_brick_stairs": 22982,
	"tuff_brick_wall": 23054,
	"tuff_bricks": 22964,
	"tuff_slab": 22145,
	"tuff_stairs": 22159,
	"tuff_wall": 22231,
	"turtle_egg": 13811,
	"twisting_vines": 19693,
	"twisting_vines_plant": 19719,
	"vault": 27746,
	"verdant_froglight": 27659,
	"vine": 7111,
	"void_air": 14013,
	"wall_torch": 2402,
	"warped_button": 20188,
	"warped_door": 20278,
	"warped_fence": 19802,
	"warped_fence_gate": 19970,
	"warped_fungus": 19647,
	"warped_hanging_sign": 5547,
	"warped_hyphae": 19641,
	"warped_nylium": 19646,
	"warped_planks": 19722,
	"warped_pressure_plate": 19738,
	"warped_roots": 19649,
	"warped_sign": 20364,
	"warped_slab": 19732,
	"warped_stairs": 20086,
	"warped_stem": 19635,
	"warped_trapdoor": 19882,
	"warped_wall_hanging_sign": 5787,
	"warped_wall_sign": 20404,
	"warped_wart_block": 19648,
	"water": 86,
	"water_cauldron": 8183,
	"waxed_chiseled_copper": 24015,
	"waxed_copper_block": 24360,
	"waxed_copper_bulb": 25771,
	"waxed_copper_door": 24979,
	"waxed_copper_grate": 25745,
	"waxed_copper_trapdoor": 25495,
	"waxed_cut_copper": 24367,
	"waxed_cut_copper_slab": 24709,
	"waxed_cut_copper_stairs": 24619,
	"waxed_exposed_chiseled_copper": 24014,
	"waxed_exposed_copper": 24362,
	"waxed_exposed_copper_bulb": 25775,
	"waxed_exposed_copper_door": 25043,
	"waxed_exposed_copper_grate": 25747,
	"waxed_exposed_copper_trapdoor": 25559,
	"waxed_exposed_cut_copper": 24366,
	"waxed_exposed_cut_copper_slab": 24703,
	"waxed_exposed_cut_copper_stairs": 24539,
	"waxed_oxidized_chiseled_copper": 24012,
	"waxed_oxidized_copper": 24363,
	"waxed_oxidized_copper_bulb": 25783,
	"waxed_oxidized_copper_door": 25107,
	"waxed_oxidized_copper_grate": 25751,
	"waxed_oxidized_copper_trapdoor": 25623,
	"waxed_oxidized_cut_copper": 24364,
	"waxed_oxidized_cut_copper_slab": 24691,
	"waxed_oxidized_cut_copper_stairs": 24379,
	"waxed_weathered_chiseled_copper": 24013,
	"waxed_weathered_copper": 24361,
	"waxed_weathered_copper_bulb": 25779,
	"waxed_weathered_copper_door": 25171,
	"waxed_weathered_copper_grate": 25749,
	"waxed_weathered_copper_trapdoor": 25687,
	"waxed_weathered_cut_copper": 24365,
	"waxed_weathered_cut_copper_slab": 24697,
	"waxed_weathered_cut_copper_stairs": 24459,
	"weathered_chiseled_copper": 24009,
	"weathered_copper": 24000,
	"weathered_copper_bulb": 25763,
	"weathered_copper_door": 24915,
	"weathered_copper_grate": 25741,
	"weathered_copper_trapdoor": 25431,
	"weathered_cut_copper": 24005,
	"weathered_cut_copper_slab": 24345,
	"weathered_cut_copper_stairs": 24107,
	"weeping_vines": 19666,
	"weeping_vines_plant": 19692,
	"wet_sponge": 561,
	"wheat": 4342,
	"white_banner": 11648,
	"white_bed": 1734,
	"white_candle": 21804,
	"white_candle_cake": 22060,
	"white_carpet": 11617,
	"white_concrete": 13751,
	"white_concrete_powder": 13767,
	"white_glazed_terracotta": 13687,
	"white_shulker_box": 13595,
	"white_stained_glass": 6124,
	"white_stained_glass_pane": 10212,
	"white_terracotta": 10165,
	"white_tulip": 2129,
	"white_wall_banner": 11904,
	"white_wool": 2093,
	"wildflowers": 25903,
	"wither_rose": 2133,
	"wither_skeleton_skull": 9692,
	"wither_skeleton_wall_skull": 9709,
	"yellow_banner": 11712,
	"yellow_bed": 1798,
	"yellow_candle": 21868,
	"yellow_candle_cake": 22068,
	"yellow_carpet": 11621,
	"yellow_concrete": 13755,
	"yellow_concrete_powder": 13771,
	"yellow_glazed_terracotta": 13703,
	"yellow_shulker_box": 13619,
	"yellow_stained_glass": 6128,
	"yellow_stained_glass_pane": 10340,
	"yellow_terracotta": 10169,
	"yellow_wall_banner": 11920,
	"yellow_wool": 2097,
	"zombie_head": 9732,
	"zombie_wall_head": 9749,
}

// DefaultStateByBlockID returns the default state ID for a given base block
// registry ID (the `id` field in blocks.json, NOT the same as the state ID).
// Useful for mapping item IDs to block states, since some items and blocks
// share the same numeric ID space (e.g., dirt item id=28, dirt block id=9).
var DefaultStateByBlockID = map[int32]Block{
	415: 9501, // acacia_button
	617: 12984, // acacia_door
	608: 12620, // acacia_fence
	599: 12308, // acacia_fence_gate
	224: 5163, // acacia_hanging_sign
	92: 391, // acacia_leaves
	53: 149, // acacia_log
	17: 19, // acacia_planks
	252: 5901, // acacia_pressure_plate
	29: 37, // acacia_sapling
	200: 4463, // acacia_sign
	571: 12078, // acacia_slab
	484: 10704, // acacia_stairs
	305: 6411, // acacia_trapdoor
	236: 5731, // acacia_wall_hanging_sign
	214: 4883, // acacia_wall_sign
	75: 214, // acacia_wood
	450: 10142, // activator_rail
	0: 0, // air
	161: 2125, // allium
	938: 22091, // amethyst_block
	940: 22102, // amethyst_cluster
	876: 20508, // ancient_debris
	6: 6, // andesite
	788: 15194, // andesite_slab
	775: 14828, // andesite_stairs
	800: 17810, // andesite_wall
	435: 9916, // anvil
	332: 7060, // attached_melon_stem
	331: 7056, // attached_pumpkin_stem
	1047: 25884, // azalea
	97: 531, // azalea_leaves
	162: 2126, // azure_bluet
	760: 14000, // bamboo
	60: 169, // bamboo_block
	420: 9621, // bamboo_button
	622: 13304, // bamboo_door
	613: 12780, // bamboo_fence
	604: 12468, // bamboo_fence_gate
	232: 5675, // bamboo_hanging_sign
	24: 28, // bamboo_mosaic
	577: 12114, // bamboo_mosaic_slab
	490: 11184, // bamboo_mosaic_stairs
	23: 27, // bamboo_planks
	257: 5911, // bamboo_pressure_plate
	759: 13999, // bamboo_sapling
	206: 4655, // bamboo_sign
	576: 12108, // bamboo_slab
	489: 11104, // bamboo_stairs
	310: 6731, // bamboo_trapdoor
	244: 5795, // bamboo_wall_hanging_sign
	220: 4931, // bamboo_wall_sign
	807: 19464, // barrel
	492: 11255, // barrier
	275: 6032, // basalt
	377: 8702, // beacon
	34: 85, // bedrock
	871: 20457, // bee_nest
	872: 20481, // beehive
	633: 13532, // beetroots
	816: 19527, // bell
	1054: 25937, // big_dripleaf
	1055: 25969, // big_dripleaf_stem
	413: 9453, // birch_button
	615: 12856, // birch_door
	606: 12556, // birch_fence
	597: 12244, // birch_fence_gate
	223: 5099, // birch_hanging_sign
	90: 335, // birch_leaves
	51: 143, // birch_log
	15: 17, // birch_planks
	250: 5897, // birch_pressure_plate
	27: 33, // birch_sapling
	199: 4431, // birch_sign
	569: 12066, // birch_slab
	374: 8541, // birch_stairs
	303: 6283, // birch_trapdoor
	235: 5723, // birch_wall_hanging_sign
	213: 4875, // birch_wall_sign
	73: 208, // birch_wood
	546: 11888, // black_banner
	125: 1974, // black_bed
	920: 22044, // black_candle
	937: 22090, // black_candle_cake
	521: 11632, // black_carpet
	693: 13766, // black_concrete
	709: 13782, // black_concrete_powder
	677: 13747, // black_glazed_terracotta
	661: 13685, // black_shulker_box
	300: 6139, // black_stained_glass
	483: 10692, // black_stained_glass_pane
	467: 10180, // black_terracotta
	562: 11964, // black_wall_banner
	155: 2108, // black_wool
	884: 20520, // blackstone
	887: 20928, // blackstone_slab
	885: 20532, // blackstone_stairs
	886: 20604, // blackstone_wall
	809: 19484, // blast_furnace
	542: 11824, // blue_banner
	121: 1910, // blue_bed
	916: 21980, // blue_candle
	933: 22082, // blue_candle_cake
	517: 11628, // blue_carpet
	689: 13762, // blue_concrete
	705: 13778, // blue_concrete_powder
	673: 13731, // blue_glazed_terracotta
	757: 13996, // blue_ice
	160: 2124, // blue_orchid
	657: 13661, // blue_shulker_box
	296: 6135, // blue_stained_glass
	479: 10564, // blue_stained_glass_pane
	463: 10176, // blue_terracotta
	558: 11948, // blue_wall_banner
	151: 2104, // blue_wool
	642: 13570, // bone_block
	177: 2142, // bookshelf
	732: 13880, // brain_coral
	722: 13864, // brain_coral_block
	742: 13900, // brain_coral_fan
	752: 13956, // brain_coral_wall_fan
	355: 8181, // brewing_stand
	584: 12156, // brick_slab
	339: 7411, // brick_stairs
	792: 15218, // brick_wall
	175: 2139, // bricks
	543: 11840, // brown_banner
	122: 1926, // brown_bed
	917: 21996, // brown_candle
	934: 22084, // brown_candle_cake
	518: 11629, // brown_carpet
	690: 13763, // brown_concrete
	706: 13779, // brown_concrete_powder
	674: 13735, // brown_glazed_terracotta
	171: 2135, // brown_mushroom
	323: 6792, // brown_mushroom_block
	658: 13667, // brown_shulker_box
	297: 6136, // brown_stained_glass
	480: 10596, // brown_stained_glass_pane
	464: 10177, // brown_terracotta
	559: 11952, // brown_wall_banner
	152: 2105, // brown_wool
	764: 14015, // bubble_column
	733: 13882, // bubble_coral
	723: 13865, // bubble_coral_block
	743: 13902, // bubble_coral_fan
	753: 13964, // bubble_coral_wall_fan
	939: 22092, // budding_amethyst
	133: 2051, // bush
	266: 5960, // cactus
	267: 5976, // cactus_flower
	283: 6053, // cake
	958: 23376, // calcite
	962: 23476, // calibrated_sculk_sensor
	819: 19569, // campfire
	904: 21788, // candle
	921: 22058, // candle_cake
	409: 9380, // carrots
	810: 19491, // cartography_table
	281: 6045, // carved_pumpkin
	356: 8182, // cauldron
	763: 14014, // cave_air
	1044: 25830, // cave_vines
	1045: 25882, // cave_vines_plant
	327: 7019, // chain
	637: 13556, // chain_command_block
	416: 9525, // cherry_button
	618: 13048, // cherry_door
	609: 12652, // cherry_fence
	600: 12340, // cherry_fence_gate
	225: 5227, // cherry_hanging_sign
	93: 419, // cherry_leaves
	54: 152, // cherry_log
	18: 20, // cherry_planks
	253: 5903, // cherry_pressure_plate
	30: 39, // cherry_sapling
	201: 4495, // cherry_sign
	572: 12084, // cherry_slab
	485: 10784, // cherry_stairs
	306: 6475, // cherry_trapdoor
	237: 5739, // cherry_wall_hanging_sign
	215: 4891, // cherry_wall_sign
	76: 217, // cherry_wood
	188: 3019, // chest
	436: 9920, // chipped_anvil
	178: 2206, // chiseled_bookshelf
	980: 24011, // chiseled_copper
	1077: 27643, // chiseled_deepslate
	901: 21782, // chiseled_nether_bricks
	891: 20934, // chiseled_polished_blackstone
	447: 10045, // chiseled_quartz_block
	564: 11969, // chiseled_red_sandstone
	349: 8055, // chiseled_resin_bricks
	107: 579, // chiseled_sandstone
	314: 6783, // chiseled_stone_bricks
	952: 22963, // chiseled_tuff
	957: 23375, // chiseled_tuff_bricks
	625: 13427, // chorus_flower
	624: 13426, // chorus_plant
	268: 5977, // clay
	1101: 27942, // closed_eyeblossom
	523: 11634, // coal_block
	46: 133, // coal_ore
	10: 11, // coarse_dirt
	1061: 25999, // cobbled_deepslate
	1063: 26083, // cobbled_deepslate_slab
	1062: 26011, // cobbled_deepslate_stairs
	1064: 26089, // cobbled_deepslate_wall
	12: 14, // cobblestone
	583: 12150, // cobblestone_slab
	210: 4789, // cobblestone_stairs
	378: 8706, // cobblestone_wall
	129: 2047, // cobweb
	365: 8203, // cocoa
	376: 8696, // command_block
	441: 9985, // comparator
	869: 20432, // composter
	758: 13997, // conduit
	967: 23998, // copper_block
	1033: 25755, // copper_bulb
	1009: 24723, // copper_door
	1025: 25737, // copper_grate
	971: 24002, // copper_ore
	1017: 25239, // copper_trapdoor
	168: 2132, // cornflower
	1078: 27644, // cracked_deepslate_bricks
	1079: 27645, // cracked_deepslate_tiles
	902: 21783, // cracked_nether_bricks
	890: 20933, // cracked_polished_blackstone_bricks
	313: 6782, // cracked_stone_bricks
	1093: 27727, // crafter
	193: 4341, // crafting_table
	186: 2927, // creaking_heart
	429: 9812, // creeper_head
	430: 9829, // creeper_wall_head
	857: 20164, // crimson_button
	859: 20214, // crimson_door
	849: 19770, // crimson_fence
	853: 19938, // crimson_fence_gate
	836: 19664, // crimson_fungus
	229: 5483, // crimson_hanging_sign
	833: 19658, // crimson_hyphae
	835: 19663, // crimson_nylium
	843: 19721, // crimson_planks
	847: 19736, // crimson_pressure_plate
	842: 19720, // crimson_roots
	861: 20332, // crimson_sign
	845: 19726, // crimson_slab
	855: 20006, // crimson_stairs
	831: 19652, // crimson_stem
	851: 19818, // crimson_trapdoor
	242: 5779, // crimson_wall_hanging_sign
	863: 20396, // crimson_wall_sign
	877: 20509, // crying_obsidian
	976: 24007, // cut_copper
	992: 24357, // cut_copper_slab
	988: 24267, // cut_copper_stairs
	565: 11970, // cut_red_sandstone
	590: 12192, // cut_red_sandstone_slab
	108: 580, // cut_sandstone
	581: 12138, // cut_sandstone_slab
	540: 11792, // cyan_banner
	119: 1878, // cyan_bed
	914: 21948, // cyan_candle
	931: 22078, // cyan_candle_cake
	515: 11626, // cyan_carpet
	687: 13760, // cyan_concrete
	703: 13776, // cyan_concrete_powder
	671: 13723, // cyan_glazed_terracotta
	655: 13649, // cyan_shulker_box
	294: 6133, // cyan_stained_glass
	477: 10500, // cyan_stained_glass_pane
	461: 10174, // cyan_terracotta
	556: 11940, // cyan_wall_banner
	149: 2102, // cyan_wool
	437: 9924, // damaged_anvil
	157: 2121, // dandelion
	417: 9549, // dark_oak_button
	619: 13112, // dark_oak_door
	610: 12684, // dark_oak_fence
	601: 12372, // dark_oak_fence_gate
	227: 5355, // dark_oak_hanging_sign
	94: 447, // dark_oak_leaves
	55: 155, // dark_oak_log
	19: 21, // dark_oak_planks
	254: 5905, // dark_oak_pressure_plate
	31: 41, // dark_oak_sapling
	203: 4559, // dark_oak_sign
	573: 12090, // dark_oak_slab
	486: 10864, // dark_oak_stairs
	307: 6539, // dark_oak_trapdoor
	239: 5755, // dark_oak_wall_hanging_sign
	217: 4907, // dark_oak_wall_sign
	77: 220, // dark_oak_wood
	497: 11354, // dark_prismarine
	503: 11610, // dark_prismarine_slab
	500: 11526, // dark_prismarine_stairs
	442: 10016, // daylight_detector
	727: 13870, // dead_brain_coral
	717: 13859, // dead_brain_coral_block
	737: 13890, // dead_brain_coral_fan
	747: 13916, // dead_brain_coral_wall_fan
	728: 13872, // dead_bubble_coral
	718: 13860, // dead_bubble_coral_block
	738: 13892, // dead_bubble_coral_fan
	748: 13924, // dead_bubble_coral_wall_fan
	132: 2050, // dead_bush
	729: 13874, // dead_fire_coral
	719: 13861, // dead_fire_coral_block
	739: 13894, // dead_fire_coral_fan
	749: 13932, // dead_fire_coral_wall_fan
	730: 13876, // dead_horn_coral
	720: 13862, // dead_horn_coral_block
	740: 13896, // dead_horn_coral_fan
	750: 13940, // dead_horn_coral_wall_fan
	726: 13868, // dead_tube_coral
	716: 13858, // dead_tube_coral_block
	736: 13888, // dead_tube_coral_fan
	746: 13908, // dead_tube_coral_wall_fan
	1092: 27675, // decorated_pot
	1060: 25997, // deepslate
	1075: 27316, // deepslate_brick_slab
	1074: 27244, // deepslate_brick_stairs
	1076: 27322, // deepslate_brick_wall
	1073: 27232, // deepslate_bricks
	47: 134, // deepslate_coal_ore
	972: 24003, // deepslate_copper_ore
	191: 4339, // deepslate_diamond_ore
	368: 8296, // deepslate_emerald_ore
	43: 130, // deepslate_gold_ore
	45: 132, // deepslate_iron_ore
	103: 564, // deepslate_lapis_ore
	259: 5915, // deepslate_redstone_ore
	1071: 26905, // deepslate_tile_slab
	1070: 26833, // deepslate_tile_stairs
	1072: 26911, // deepslate_tile_wall
	1069: 26821, // deepslate_tiles
	127: 2024, // detector_rail
	192: 4340, // diamond_block
	190: 4338, // diamond_ore
	4: 4, // diorite
	791: 15212, // diorite_slab
	778: 15068, // diorite_stairs
	804: 19106, // diorite_wall
	9: 10, // dirt
	634: 13536, // dirt_path
	105: 567, // dispenser
	363: 8200, // dragon_egg
	431: 9852, // dragon_head
	432: 9869, // dragon_wall_head
	715: 13827, // dried_ghast
	712: 13810, // dried_kelp_block
	1043: 25828, // dripstone_block
	451: 10154, // dropper
	372: 8449, // emerald_block
	367: 8295, // emerald_ore
	354: 8173, // enchanting_table
	635: 13537, // end_gateway
	360: 8190, // end_portal
	361: 8195, // end_portal_frame
	623: 13361, // end_rod
	362: 8199, // end_stone
	784: 15170, // end_stone_brick_slab
	770: 14428, // end_stone_brick_stairs
	803: 18782, // end_stone_brick_wall
	629: 13517, // end_stone_bricks
	369: 8298, // ender_chest
	979: 24010, // exposed_chiseled_copper
	968: 23999, // exposed_copper
	1034: 25759, // exposed_copper_bulb
	1010: 24787, // exposed_copper_door
	1026: 25739, // exposed_copper_grate
	1018: 25303, // exposed_copper_trapdoor
	975: 24006, // exposed_cut_copper
	991: 24351, // exposed_cut_copper_slab
	987: 24187, // exposed_cut_copper_stairs
	195: 4350, // farmland
	131: 2049, // fern
	183: 2437, // fire
	734: 13884, // fire_coral
	724: 13866, // fire_coral_block
	744: 13904, // fire_coral_fan
	754: 13972, // fire_coral_wall_fan
	1104: 27945, // firefly_bush
	811: 19492, // fletching_table
	380: 9351, // flower_pot
	1048: 25885, // flowering_azalea
	98: 559, // flowering_azalea_leaves
	1090: 27664, // frogspawn
	638: 13562, // frosted_ice
	196: 4359, // furnace
	895: 21345, // gilded_blackstone
	101: 562, // glass
	328: 7053, // glass_pane
	336: 7239, // glow_lichen
	279: 6042, // glowstone
	173: 2137, // gold_block
	42: 129, // gold_ore
	2: 2, // granite
	787: 15188, // granite_slab
	774: 14748, // granite_stairs
	796: 16514, // granite_wall
	8: 9, // grass_block
	40: 124, // gravel
	538: 11760, // gray_banner
	117: 1846, // gray_bed
	912: 21916, // gray_candle
	929: 22074, // gray_candle_cake
	513: 11624, // gray_carpet
	685: 13758, // gray_concrete
	701: 13774, // gray_concrete_powder
	669: 13715, // gray_glazed_terracotta
	653: 13637, // gray_shulker_box
	292: 6131, // gray_stained_glass
	475: 10436, // gray_stained_glass_pane
	459: 10172, // gray_terracotta
	554: 11932, // gray_wall_banner
	147: 2100, // gray_wool
	544: 11856, // green_banner
	123: 1942, // green_bed
	918: 22012, // green_candle
	935: 22086, // green_candle_cake
	519: 11630, // green_carpet
	691: 13764, // green_concrete
	707: 13780, // green_concrete_powder
	675: 13739, // green_glazed_terracotta
	659: 13673, // green_shulker_box
	298: 6137, // green_stained_glass
	481: 10628, // green_stained_glass_pane
	465: 10178, // green_terracotta
	560: 11956, // green_wall_banner
	153: 2106, // green_wool
	812: 19497, // grindstone
	1057: 25993, // hanging_roots
	505: 11615, // hay_block
	1096: 27775, // heavy_core
	440: 9968, // heavy_weighted_pressure_plate
	873: 20505, // honey_block
	874: 20506, // honeycomb_block
	445: 10034, // hopper
	735: 13886, // horn_coral
	725: 13867, // horn_coral_block
	745: 13906, // horn_coral_fan
	755: 13980, // horn_coral_wall_fan
	264: 5958, // ice
	322: 6791, // infested_chiseled_stone_bricks
	318: 6787, // infested_cobblestone
	321: 6790, // infested_cracked_stone_bricks
	1080: 27647, // infested_deepslate
	320: 6789, // infested_mossy_stone_bricks
	317: 6786, // infested_stone
	319: 6788, // infested_stone_bricks
	326: 7015, // iron_bars
	174: 2138, // iron_block
	247: 5839, // iron_door
	44: 131, // iron_ore
	494: 11303, // iron_trapdoor
	282: 6049, // jack_o_lantern
	866: 20425, // jigsaw
	270: 5995, // jukebox
	414: 9477, // jungle_button
	616: 12920, // jungle_door
	607: 12588, // jungle_fence
	598: 12276, // jungle_fence_gate
	226: 5291, // jungle_hanging_sign
	91: 363, // jungle_leaves
	52: 146, // jungle_log
	16: 18, // jungle_planks
	251: 5899, // jungle_pressure_plate
	28: 35, // jungle_sapling
	202: 4527, // jungle_sign
	570: 12072, // jungle_slab
	375: 8621, // jungle_stairs
	304: 6347, // jungle_trapdoor
	238: 5747, // jungle_wall_hanging_sign
	216: 4899, // jungle_wall_sign
	74: 211, // jungle_wood
	710: 13783, // kelp
	711: 13809, // kelp_plant
	208: 4751, // ladder
	817: 19561, // lantern
	104: 565, // lapis_block
	102: 563, // lapis_ore
	941: 22114, // large_amethyst_bud
	530: 11647, // large_fern
	36: 102, // lava
	358: 8186, // lava_cauldron
	1052: 25919, // leaf_litter
	813: 19508, // lectern
	245: 5811, // lever
	493: 11287, // light
	534: 11696, // light_blue_banner
	113: 1782, // light_blue_bed
	908: 21852, // light_blue_candle
	925: 22066, // light_blue_candle_cake
	509: 11620, // light_blue_carpet
	681: 13754, // light_blue_concrete
	697: 13770, // light_blue_concrete_powder
	665: 13699, // light_blue_glazed_terracotta
	649: 13613, // light_blue_shulker_box
	288: 6127, // light_blue_stained_glass
	471: 10308, // light_blue_stained_glass_pane
	455: 10168, // light_blue_terracotta
	550: 11916, // light_blue_wall_banner
	143: 2096, // light_blue_wool
	539: 11776, // light_gray_banner
	118: 1862, // light_gray_bed
	913: 21932, // light_gray_candle
	930: 22076, // light_gray_candle_cake
	514: 11625, // light_gray_carpet
	686: 13759, // light_gray_concrete
	702: 13775, // light_gray_concrete_powder
	670: 13719, // light_gray_glazed_terracotta
	654: 13643, // light_gray_shulker_box
	293: 6132, // light_gray_stained_glass
	476: 10468, // light_gray_stained_glass_pane
	460: 10173, // light_gray_terracotta
	555: 11936, // light_gray_wall_banner
	148: 2101, // light_gray_wool
	439: 9952, // light_weighted_pressure_plate
	1041: 25803, // lightning_rod
	526: 11639, // lilac
	170: 2134, // lily_of_the_valley
	343: 7642, // lily_pad
	536: 11728, // lime_banner
	115: 1814, // lime_bed
	910: 21884, // lime_candle
	927: 22070, // lime_candle_cake
	511: 11622, // lime_carpet
	683: 13756, // lime_concrete
	699: 13772, // lime_concrete_powder
	667: 13707, // lime_glazed_terracotta
	651: 13625, // lime_shulker_box
	290: 6129, // lime_stained_glass
	473: 10372, // lime_stained_glass_pane
	457: 10170, // lime_terracotta
	552: 11924, // lime_wall_banner
	145: 2098, // lime_wool
	883: 20519, // lodestone
	806: 19459, // loom
	533: 11680, // magenta_banner
	112: 1766, // magenta_bed
	907: 21836, // magenta_candle
	924: 22064, // magenta_candle_cake
	508: 11619, // magenta_carpet
	680: 13753, // magenta_concrete
	696: 13769, // magenta_concrete_powder
	664: 13695, // magenta_glazed_terracotta
	648: 13607, // magenta_shulker_box
	287: 6126, // magenta_stained_glass
	470: 10276, // magenta_stained_glass_pane
	454: 10167, // magenta_terracotta
	549: 11912, // magenta_wall_banner
	142: 2095, // magenta_wool
	639: 13566, // magma_block
	419: 9597, // mangrove_button
	621: 13240, // mangrove_door
	612: 12748, // mangrove_fence
	603: 12436, // mangrove_fence_gate
	231: 5611, // mangrove_hanging_sign
	96: 503, // mangrove_leaves
	57: 161, // mangrove_log
	22: 26, // mangrove_planks
	256: 5909, // mangrove_pressure_plate
	33: 50, // mangrove_propagule
	58: 164, // mangrove_roots
	205: 4623, // mangrove_sign
	575: 12102, // mangrove_slab
	488: 11024, // mangrove_stairs
	309: 6667, // mangrove_trapdoor
	241: 5771, // mangrove_wall_hanging_sign
	219: 4923, // mangrove_wall_sign
	78: 223, // mangrove_wood
	942: 22126, // medium_amethyst_bud
	330: 7055, // melon
	334: 7072, // melon_stem
	1053: 25935, // moss_block
	1049: 25886, // moss_carpet
	179: 2399, // mossy_cobblestone
	783: 15164, // mossy_cobblestone_slab
	769: 14348, // mossy_cobblestone_stairs
	379: 9030, // mossy_cobblestone_wall
	781: 15152, // mossy_stone_brick_slab
	767: 14188, // mossy_stone_brick_stairs
	795: 16190, // mossy_stone_brick_wall
	312: 6781, // mossy_stone_bricks
	156: 2109, // moving_piston
	1059: 25995, // mud
	586: 12168, // mud_brick_slab
	341: 7571, // mud_brick_stairs
	798: 17162, // mud_brick_wall
	316: 6785, // mud_bricks
	59: 166, // muddy_mangrove_roots
	325: 6920, // mushroom_stem
	342: 7641, // mycelium
	351: 8088, // nether_brick_fence
	587: 12174, // nether_brick_slab
	352: 8100, // nether_brick_stairs
	799: 17486, // nether_brick_wall
	350: 8056, // nether_bricks
	48: 135, // nether_gold_ore
	280: 6043, // nether_portal
	444: 10033, // nether_quartz_ore
	830: 19650, // nether_sprouts
	353: 8169, // nether_wart
	640: 13567, // nether_wart_block
	875: 20507, // netherite_block
	272: 6028, // netherrack
	109: 582, // note_block
	411: 9405, // oak_button
	207: 4697, // oak_door
	271: 6027, // oak_fence
	338: 7375, // oak_fence_gate
	221: 4971, // oak_hanging_sign
	88: 279, // oak_leaves
	49: 137, // oak_log
	13: 15, // oak_planks
	248: 5893, // oak_pressure_plate
	25: 29, // oak_sapling
	197: 4367, // oak_sign
	567: 12054, // oak_slab
	187: 2949, // oak_stairs
	301: 6155, // oak_trapdoor
	233: 5707, // oak_wall_hanging_sign
	211: 4859, // oak_wall_sign
	71: 202, // oak_wood
	644: 13578, // observer
	180: 2400, // obsidian
	1087: 27656, // ochre_froglight
	1100: 27941, // open_eyeblossom
	532: 11664, // orange_banner
	111: 1750, // orange_bed
	906: 21820, // orange_candle
	923: 22062, // orange_candle_cake
	507: 11618, // orange_carpet
	679: 13752, // orange_concrete
	695: 13768, // orange_concrete_powder
	663: 13691, // orange_glazed_terracotta
	647: 13601, // orange_shulker_box
	286: 6125, // orange_stained_glass
	469: 10244, // orange_stained_glass_pane
	453: 10166, // orange_terracotta
	164: 2128, // orange_tulip
	548: 11908, // orange_wall_banner
	141: 2094, // orange_wool
	167: 2131, // oxeye_daisy
	977: 24008, // oxidized_chiseled_copper
	970: 24001, // oxidized_copper
	1036: 25767, // oxidized_copper_bulb
	1011: 24851, // oxidized_copper_door
	1028: 25743, // oxidized_copper_grate
	1019: 25367, // oxidized_copper_trapdoor
	973: 24004, // oxidized_cut_copper
	989: 24339, // oxidized_cut_copper_slab
	985: 24027, // oxidized_cut_copper_stairs
	524: 11635, // packed_ice
	315: 6784, // packed_mud
	1099: 27939, // pale_hanging_moss
	1097: 27776, // pale_moss_block
	1098: 27777, // pale_moss_carpet
	418: 9573, // pale_oak_button
	620: 13176, // pale_oak_door
	611: 12716, // pale_oak_fence
	602: 12404, // pale_oak_fence_gate
	228: 5419, // pale_oak_hanging_sign
	95: 475, // pale_oak_leaves
	56: 158, // pale_oak_log
	21: 25, // pale_oak_planks
	255: 5907, // pale_oak_pressure_plate
	32: 43, // pale_oak_sapling
	204: 4591, // pale_oak_sign
	574: 12096, // pale_oak_slab
	487: 10944, // pale_oak_stairs
	308: 6603, // pale_oak_trapdoor
	240: 5763, // pale_oak_wall_hanging_sign
	218: 4915, // pale_oak_wall_sign
	20: 23, // pale_oak_wood
	1089: 27662, // pearlescent_froglight
	528: 11643, // peony
	582: 12144, // petrified_oak_slab
	433: 9892, // piglin_head
	434: 9909, // piglin_wall_head
	537: 11744, // pink_banner
	116: 1830, // pink_bed
	911: 21900, // pink_candle
	928: 22072, // pink_candle_cake
	512: 11623, // pink_carpet
	684: 13757, // pink_concrete
	700: 13773, // pink_concrete_powder
	668: 13711, // pink_glazed_terracotta
	1050: 25887, // pink_petals
	652: 13631, // pink_shulker_box
	291: 6130, // pink_stained_glass
	474: 10404, // pink_stained_glass_pane
	458: 10171, // pink_terracotta
	166: 2130, // pink_tulip
	553: 11928, // pink_wall_banner
	146: 2099, // pink_wool
	138: 2063, // piston
	139: 2071, // piston_head
	631: 13521, // pitcher_crop
	632: 13531, // pitcher_plant
	427: 9772, // player_head
	428: 9789, // player_wall_head
	11: 13, // podzol
	1042: 25813, // pointed_dripstone
	7: 7, // polished_andesite
	790: 15206, // polished_andesite_slab
	777: 14988, // polished_andesite_stairs
	276: 6035, // polished_basalt
	888: 20931, // polished_blackstone
	892: 20938, // polished_blackstone_brick_slab
	893: 20952, // polished_blackstone_brick_stairs
	894: 21024, // polished_blackstone_brick_wall
	889: 20932, // polished_blackstone_bricks
	899: 21443, // polished_blackstone_button
	898: 21433, // polished_blackstone_pressure_plate
	897: 21429, // polished_blackstone_slab
	896: 21357, // polished_blackstone_stairs
	900: 21461, // polished_blackstone_wall
	1065: 26410, // polished_deepslate
	1067: 26494, // polished_deepslate_slab
	1066: 26422, // polished_deepslate_stairs
	1068: 26500, // polished_deepslate_wall
	5: 5, // polished_diorite
	782: 15158, // polished_diorite_slab
	768: 14268, // polished_diorite_stairs
	3: 3, // polished_granite
	779: 15140, // polished_granite_slab
	765: 14028, // polished_granite_stairs
	948: 22552, // polished_tuff
	949: 22556, // polished_tuff_slab
	950: 22570, // polished_tuff_stairs
	951: 22642, // polished_tuff_wall
	159: 2123, // poppy
	410: 9388, // potatoes
	386: 9357, // potted_acacia_sapling
	395: 9366, // potted_allium
	1085: 27653, // potted_azalea_bush
	396: 9367, // potted_azure_bluet
	761: 14012, // potted_bamboo
	384: 9355, // potted_birch_sapling
	394: 9365, // potted_blue_orchid
	406: 9377, // potted_brown_mushroom
	408: 9379, // potted_cactus
	387: 9358, // potted_cherry_sapling
	1103: 27944, // potted_closed_eyeblossom
	402: 9373, // potted_cornflower
	879: 20515, // potted_crimson_fungus
	881: 20517, // potted_crimson_roots
	392: 9363, // potted_dandelion
	388: 9359, // potted_dark_oak_sapling
	407: 9378, // potted_dead_bush
	391: 9362, // potted_fern
	1086: 27654, // potted_flowering_azalea_bush
	385: 9356, // potted_jungle_sapling
	403: 9374, // potted_lily_of_the_valley
	390: 9361, // potted_mangrove_propagule
	382: 9353, // potted_oak_sapling
	1102: 27943, // potted_open_eyeblossom
	398: 9369, // potted_orange_tulip
	401: 9372, // potted_oxeye_daisy
	389: 9360, // potted_pale_oak_sapling
	400: 9371, // potted_pink_tulip
	393: 9364, // potted_poppy
	405: 9376, // potted_red_mushroom
	397: 9368, // potted_red_tulip
	383: 9354, // potted_spruce_sapling
	381: 9352, // potted_torchflower
	880: 20516, // potted_warped_fungus
	882: 20518, // potted_warped_roots
	399: 9370, // potted_white_tulip
	404: 9375, // potted_wither_rose
	960: 23378, // powder_snow
	359: 8187, // powder_snow_cauldron
	126: 2000, // powered_rail
	495: 11352, // prismarine
	502: 11604, // prismarine_brick_slab
	499: 11446, // prismarine_brick_stairs
	496: 11353, // prismarine_bricks
	501: 11598, // prismarine_slab
	498: 11366, // prismarine_stairs
	793: 15542, // prismarine_wall
	329: 7054, // pumpkin
	333: 7064, // pumpkin_stem
	541: 11808, // purple_banner
	120: 1894, // purple_bed
	915: 21964, // purple_candle
	932: 22080, // purple_candle_cake
	516: 11627, // purple_carpet
	688: 13761, // purple_concrete
	704: 13777, // purple_concrete_powder
	672: 13727, // purple_glazed_terracotta
	656: 13655, // purple_shulker_box
	295: 6134, // purple_stained_glass
	478: 10532, // purple_stained_glass_pane
	462: 10175, // purple_terracotta
	557: 11944, // purple_wall_banner
	150: 2103, // purple_wool
	626: 13433, // purpur_block
	627: 13435, // purpur_pillar
	591: 12198, // purpur_slab
	628: 13448, // purpur_stairs
	446: 10044, // quartz_block
	903: 21784, // quartz_bricks
	448: 10047, // quartz_pillar
	588: 12180, // quartz_slab
	449: 10060, // quartz_stairs
	209: 4759, // rail
	1083: 27651, // raw_copper_block
	1084: 27652, // raw_gold_block
	1082: 27650, // raw_iron_block
	545: 11872, // red_banner
	124: 1958, // red_bed
	919: 22028, // red_candle
	936: 22088, // red_candle_cake
	520: 11631, // red_carpet
	692: 13765, // red_concrete
	708: 13781, // red_concrete_powder
	676: 13743, // red_glazed_terracotta
	172: 2136, // red_mushroom
	324: 6856, // red_mushroom_block
	789: 15200, // red_nether_brick_slab
	776: 14908, // red_nether_brick_stairs
	801: 18134, // red_nether_brick_wall
	641: 13568, // red_nether_bricks
	39: 123, // red_sand
	563: 11968, // red_sandstone
	589: 12186, // red_sandstone_slab
	566: 11982, // red_sandstone_stairs
	794: 15866, // red_sandstone_wall
	660: 13679, // red_shulker_box
	299: 6138, // red_stained_glass
	482: 10660, // red_stained_glass_pane
	466: 10179, // red_terracotta
	163: 2127, // red_tulip
	561: 11960, // red_wall_banner
	154: 2107, // red_wool
	443: 10032, // redstone_block
	364: 8202, // redstone_lamp
	258: 5913, // redstone_ore
	260: 5916, // redstone_torch
	261: 5918, // redstone_wall_torch
	189: 4202, // redstone_wire
	1091: 27665, // reinforced_deepslate
	284: 6063, // repeater
	636: 13544, // repeating_command_block
	344: 7643, // resin_block
	347: 7728, // resin_brick_slab
	346: 7656, // resin_brick_stairs
	348: 7734, // resin_brick_wall
	345: 7644, // resin_bricks
	337: 7367, // resin_clump
	878: 20510, // respawn_anchor
	1058: 25994, // rooted_dirt
	527: 11641, // rose_bush
	37: 118, // sand
	106: 578, // sandstone
	580: 12132, // sandstone_slab
	366: 8226, // sandstone_stairs
	802: 18458, // sandstone_wall
	805: 19458, // scaffolding
	963: 23859, // sculk
	965: 23989, // sculk_catalyst
	961: 23380, // sculk_sensor
	966: 23997, // sculk_shrieker
	964: 23987, // sculk_vein
	504: 11613, // sea_lantern
	756: 13988, // sea_pickle
	136: 2054, // seagrass
	134: 2052, // short_dry_grass
	130: 2048, // short_grass
	837: 19665, // shroomlight
	645: 13589, // shulker_box
	421: 9652, // skeleton_skull
	422: 9669, // skeleton_wall_skull
	491: 11253, // slime_block
	943: 22138, // small_amethyst_bud
	1056: 25979, // small_dripleaf
	814: 19521, // smithing_table
	808: 19476, // smoker
	1081: 27649, // smooth_basalt
	594: 12203, // smooth_quartz
	786: 15182, // smooth_quartz_slab
	773: 14668, // smooth_quartz_stairs
	595: 12204, // smooth_red_sandstone
	780: 15146, // smooth_red_sandstone_slab
	766: 14108, // smooth_red_sandstone_stairs
	593: 12202, // smooth_sandstone
	785: 15176, // smooth_sandstone_slab
	772: 14588, // smooth_sandstone_stairs
	592: 12201, // smooth_stone
	579: 12126, // smooth_stone_slab
	714: 13823, // sniffer_egg
	263: 5950, // snow
	265: 5959, // snow_block
	820: 19601, // soul_campfire
	184: 2918, // soul_fire
	818: 19565, // soul_lantern
	273: 6029, // soul_sand
	274: 6030, // soul_soil
	277: 6037, // soul_torch
	278: 6038, // soul_wall_torch
	185: 2919, // spawner
	99: 560, // sponge
	1046: 25883, // spore_blossom
	412: 9429, // spruce_button
	614: 12792, // spruce_door
	605: 12524, // spruce_fence
	596: 12212, // spruce_fence_gate
	222: 5035, // spruce_hanging_sign
	89: 307, // spruce_leaves
	50: 140, // spruce_log
	14: 16, // spruce_planks
	249: 5895, // spruce_pressure_plate
	26: 31, // spruce_sapling
	198: 4399, // spruce_sign
	568: 12060, // spruce_slab
	373: 8461, // spruce_stairs
	302: 6219, // spruce_trapdoor
	234: 5715, // spruce_wall_hanging_sign
	212: 4867, // spruce_wall_sign
	72: 205, // spruce_wood
	128: 2041, // sticky_piston
	1: 1, // stone
	585: 12162, // stone_brick_slab
	340: 7491, // stone_brick_stairs
	797: 16838, // stone_brick_wall
	311: 6780, // stone_bricks
	262: 5935, // stone_button
	246: 5827, // stone_pressure_plate
	578: 12120, // stone_slab
	771: 14508, // stone_stairs
	815: 19522, // stonecutter
	64: 181, // stripped_acacia_log
	83: 238, // stripped_acacia_wood
	70: 199, // stripped_bamboo_block
	62: 175, // stripped_birch_log
	81: 232, // stripped_birch_wood
	65: 184, // stripped_cherry_log
	84: 241, // stripped_cherry_wood
	834: 19661, // stripped_crimson_hyphae
	832: 19655, // stripped_crimson_stem
	66: 187, // stripped_dark_oak_log
	85: 244, // stripped_dark_oak_wood
	63: 178, // stripped_jungle_log
	82: 235, // stripped_jungle_wood
	69: 196, // stripped_mangrove_log
	87: 250, // stripped_mangrove_wood
	68: 193, // stripped_oak_log
	79: 226, // stripped_oak_wood
	67: 190, // stripped_pale_oak_log
	86: 247, // stripped_pale_oak_wood
	61: 172, // stripped_spruce_log
	80: 229, // stripped_spruce_wood
	825: 19644, // stripped_warped_hyphae
	823: 19638, // stripped_warped_stem
	865: 20412, // structure_block
	643: 13572, // structure_void
	269: 5978, // sugar_cane
	525: 11637, // sunflower
	41: 125, // suspicious_gravel
	38: 119, // suspicious_sand
	821: 19630, // sweet_berry_bush
	135: 2053, // tall_dry_grass
	529: 11645, // tall_grass
	137: 2056, // tall_seagrass
	870: 20441, // target
	522: 11633, // terracotta
	867: 20427, // test_block
	868: 20431, // test_instance_block
	959: 23377, // tinted_glass
	176: 2141, // tnt
	181: 2401, // torch
	158: 2122, // torchflower
	630: 13518, // torchflower_crop
	438: 9929, // trapped_chest
	1094: 27736, // trial_spawner
	371: 8448, // tripwire
	370: 8314, // tripwire_hook
	731: 13878, // tube_coral
	721: 13863, // tube_coral_block
	741: 13898, // tube_coral_fan
	751: 13948, // tube_coral_wall_fan
	944: 22141, // tuff
	954: 22968, // tuff_brick_slab
	955: 22982, // tuff_brick_stairs
	956: 23054, // tuff_brick_wall
	953: 22964, // tuff_bricks
	945: 22145, // tuff_slab
	946: 22159, // tuff_stairs
	947: 22231, // tuff_wall
	713: 13811, // turtle_egg
	840: 19693, // twisting_vines
	841: 19719, // twisting_vines_plant
	1095: 27746, // vault
	1088: 27659, // verdant_froglight
	335: 7111, // vine
	762: 14013, // void_air
	182: 2402, // wall_torch
	858: 20188, // warped_button
	860: 20278, // warped_door
	850: 19802, // warped_fence
	854: 19970, // warped_fence_gate
	827: 19647, // warped_fungus
	230: 5547, // warped_hanging_sign
	824: 19641, // warped_hyphae
	826: 19646, // warped_nylium
	844: 19722, // warped_planks
	848: 19738, // warped_pressure_plate
	829: 19649, // warped_roots
	862: 20364, // warped_sign
	846: 19732, // warped_slab
	856: 20086, // warped_stairs
	822: 19635, // warped_stem
	852: 19882, // warped_trapdoor
	243: 5787, // warped_wall_hanging_sign
	864: 20404, // warped_wall_sign
	828: 19648, // warped_wart_block
	35: 86, // water
	357: 8183, // water_cauldron
	984: 24015, // waxed_chiseled_copper
	993: 24360, // waxed_copper_block
	1037: 25771, // waxed_copper_bulb
	1013: 24979, // waxed_copper_door
	1029: 25745, // waxed_copper_grate
	1021: 25495, // waxed_copper_trapdoor
	1000: 24367, // waxed_cut_copper
	1008: 24709, // waxed_cut_copper_slab
	1004: 24619, // waxed_cut_copper_stairs
	983: 24014, // waxed_exposed_chiseled_copper
	995: 24362, // waxed_exposed_copper
	1038: 25775, // waxed_exposed_copper_bulb
	1014: 25043, // waxed_exposed_copper_door
	1030: 25747, // waxed_exposed_copper_grate
	1022: 25559, // waxed_exposed_copper_trapdoor
	999: 24366, // waxed_exposed_cut_copper
	1007: 24703, // waxed_exposed_cut_copper_slab
	1003: 24539, // waxed_exposed_cut_copper_stairs
	981: 24012, // waxed_oxidized_chiseled_copper
	996: 24363, // waxed_oxidized_copper
	1040: 25783, // waxed_oxidized_copper_bulb
	1015: 25107, // waxed_oxidized_copper_door
	1032: 25751, // waxed_oxidized_copper_grate
	1023: 25623, // waxed_oxidized_copper_trapdoor
	997: 24364, // waxed_oxidized_cut_copper
	1005: 24691, // waxed_oxidized_cut_copper_slab
	1001: 24379, // waxed_oxidized_cut_copper_stairs
	982: 24013, // waxed_weathered_chiseled_copper
	994: 24361, // waxed_weathered_copper
	1039: 25779, // waxed_weathered_copper_bulb
	1016: 25171, // waxed_weathered_copper_door
	1031: 25749, // waxed_weathered_copper_grate
	1024: 25687, // waxed_weathered_copper_trapdoor
	998: 24365, // waxed_weathered_cut_copper
	1006: 24697, // waxed_weathered_cut_copper_slab
	1002: 24459, // waxed_weathered_cut_copper_stairs
	978: 24009, // weathered_chiseled_copper
	969: 24000, // weathered_copper
	1035: 25763, // weathered_copper_bulb
	1012: 24915, // weathered_copper_door
	1027: 25741, // weathered_copper_grate
	1020: 25431, // weathered_copper_trapdoor
	974: 24005, // weathered_cut_copper
	990: 24345, // weathered_cut_copper_slab
	986: 24107, // weathered_cut_copper_stairs
	838: 19666, // weeping_vines
	839: 19692, // weeping_vines_plant
	100: 561, // wet_sponge
	194: 4342, // wheat
	531: 11648, // white_banner
	110: 1734, // white_bed
	905: 21804, // white_candle
	922: 22060, // white_candle_cake
	506: 11617, // white_carpet
	678: 13751, // white_concrete
	694: 13767, // white_concrete_powder
	662: 13687, // white_glazed_terracotta
	646: 13595, // white_shulker_box
	285: 6124, // white_stained_glass
	468: 10212, // white_stained_glass_pane
	452: 10165, // white_terracotta
	165: 2129, // white_tulip
	547: 11904, // white_wall_banner
	140: 2093, // white_wool
	1051: 25903, // wildflowers
	169: 2133, // wither_rose
	423: 9692, // wither_skeleton_skull
	424: 9709, // wither_skeleton_wall_skull
	535: 11712, // yellow_banner
	114: 1798, // yellow_bed
	909: 21868, // yellow_candle
	926: 22068, // yellow_candle_cake
	510: 11621, // yellow_carpet
	682: 13755, // yellow_concrete
	698: 13771, // yellow_concrete_powder
	666: 13703, // yellow_glazed_terracotta
	650: 13619, // yellow_shulker_box
	289: 6128, // yellow_stained_glass
	472: 10340, // yellow_stained_glass_pane
	456: 10169, // yellow_terracotta
	551: 11920, // yellow_wall_banner
	144: 2097, // yellow_wool
	425: 9732, // zombie_head
	426: 9749, // zombie_wall_head
}

// ItemIDToBlockState maps an item registry ID to its corresponding block default
// state ID, if the item represents a placeable block. Built by joining
// items.json (item id -> item name) with blocks.json (name -> default state).
// Lookups are O(1) and used by Player.placeBlock() to resolve what block to
// place when a player right-clicks (use_item_on) with an item in hand.
var ItemIDToBlockState = map[int32]Block{
	0: 0, // air
	1: 1, // stone
	2: 2, // granite
	3: 3, // polished_granite
	4: 4, // diorite
	5: 5, // polished_diorite
	6: 6, // andesite
	7: 7, // polished_andesite
	8: 25997, // deepslate
	9: 25999, // cobbled_deepslate
	10: 26410, // polished_deepslate
	11: 23376, // calcite
	12: 22141, // tuff
	13: 22145, // tuff_slab
	14: 22159, // tuff_stairs
	15: 22231, // tuff_wall
	16: 22963, // chiseled_tuff
	17: 22552, // polished_tuff
	18: 22556, // polished_tuff_slab
	19: 22570, // polished_tuff_stairs
	20: 22642, // polished_tuff_wall
	21: 22964, // tuff_bricks
	22: 22968, // tuff_brick_slab
	23: 22982, // tuff_brick_stairs
	24: 23054, // tuff_brick_wall
	25: 23375, // chiseled_tuff_bricks
	26: 25828, // dripstone_block
	27: 9, // grass_block
	28: 10, // dirt
	29: 11, // coarse_dirt
	30: 13, // podzol
	31: 25994, // rooted_dirt
	32: 25995, // mud
	33: 19663, // crimson_nylium
	34: 19646, // warped_nylium
	35: 14, // cobblestone
	36: 15, // oak_planks
	37: 16, // spruce_planks
	38: 17, // birch_planks
	39: 18, // jungle_planks
	40: 19, // acacia_planks
	41: 20, // cherry_planks
	42: 21, // dark_oak_planks
	43: 25, // pale_oak_planks
	44: 26, // mangrove_planks
	45: 27, // bamboo_planks
	46: 19721, // crimson_planks
	47: 19722, // warped_planks
	48: 28, // bamboo_mosaic
	49: 29, // oak_sapling
	50: 31, // spruce_sapling
	51: 33, // birch_sapling
	52: 35, // jungle_sapling
	53: 37, // acacia_sapling
	54: 39, // cherry_sapling
	55: 41, // dark_oak_sapling
	56: 43, // pale_oak_sapling
	57: 50, // mangrove_propagule
	58: 85, // bedrock
	59: 118, // sand
	60: 119, // suspicious_sand
	61: 125, // suspicious_gravel
	62: 123, // red_sand
	63: 124, // gravel
	64: 133, // coal_ore
	65: 134, // deepslate_coal_ore
	66: 131, // iron_ore
	67: 132, // deepslate_iron_ore
	68: 24002, // copper_ore
	69: 24003, // deepslate_copper_ore
	70: 129, // gold_ore
	71: 130, // deepslate_gold_ore
	72: 5913, // redstone_ore
	73: 5915, // deepslate_redstone_ore
	74: 8295, // emerald_ore
	75: 8296, // deepslate_emerald_ore
	76: 563, // lapis_ore
	77: 564, // deepslate_lapis_ore
	78: 4338, // diamond_ore
	79: 4339, // deepslate_diamond_ore
	80: 135, // nether_gold_ore
	81: 10033, // nether_quartz_ore
	82: 20508, // ancient_debris
	83: 11634, // coal_block
	84: 27650, // raw_iron_block
	85: 27651, // raw_copper_block
	86: 27652, // raw_gold_block
	87: 27775, // heavy_core
	88: 22091, // amethyst_block
	89: 22092, // budding_amethyst
	90: 2138, // iron_block
	91: 23998, // copper_block
	92: 2137, // gold_block
	93: 4340, // diamond_block
	94: 20507, // netherite_block
	95: 23999, // exposed_copper
	96: 24000, // weathered_copper
	97: 24001, // oxidized_copper
	98: 24011, // chiseled_copper
	99: 24010, // exposed_chiseled_copper
	100: 24009, // weathered_chiseled_copper
	101: 24008, // oxidized_chiseled_copper
	102: 24007, // cut_copper
	103: 24006, // exposed_cut_copper
	104: 24005, // weathered_cut_copper
	105: 24004, // oxidized_cut_copper
	106: 24267, // cut_copper_stairs
	107: 24187, // exposed_cut_copper_stairs
	108: 24107, // weathered_cut_copper_stairs
	109: 24027, // oxidized_cut_copper_stairs
	110: 24357, // cut_copper_slab
	111: 24351, // exposed_cut_copper_slab
	112: 24345, // weathered_cut_copper_slab
	113: 24339, // oxidized_cut_copper_slab
	114: 24360, // waxed_copper_block
	115: 24362, // waxed_exposed_copper
	116: 24361, // waxed_weathered_copper
	117: 24363, // waxed_oxidized_copper
	118: 24015, // waxed_chiseled_copper
	119: 24014, // waxed_exposed_chiseled_copper
	120: 24013, // waxed_weathered_chiseled_copper
	121: 24012, // waxed_oxidized_chiseled_copper
	122: 24367, // waxed_cut_copper
	123: 24366, // waxed_exposed_cut_copper
	124: 24365, // waxed_weathered_cut_copper
	125: 24364, // waxed_oxidized_cut_copper
	126: 24619, // waxed_cut_copper_stairs
	127: 24539, // waxed_exposed_cut_copper_stairs
	128: 24459, // waxed_weathered_cut_copper_stairs
	129: 24379, // waxed_oxidized_cut_copper_stairs
	130: 24709, // waxed_cut_copper_slab
	131: 24703, // waxed_exposed_cut_copper_slab
	132: 24697, // waxed_weathered_cut_copper_slab
	133: 24691, // waxed_oxidized_cut_copper_slab
	134: 137, // oak_log
	135: 140, // spruce_log
	136: 143, // birch_log
	137: 146, // jungle_log
	138: 149, // acacia_log
	139: 152, // cherry_log
	140: 158, // pale_oak_log
	141: 155, // dark_oak_log
	142: 161, // mangrove_log
	143: 164, // mangrove_roots
	144: 166, // muddy_mangrove_roots
	145: 19652, // crimson_stem
	146: 19635, // warped_stem
	147: 169, // bamboo_block
	148: 193, // stripped_oak_log
	149: 172, // stripped_spruce_log
	150: 175, // stripped_birch_log
	151: 178, // stripped_jungle_log
	152: 181, // stripped_acacia_log
	153: 184, // stripped_cherry_log
	154: 187, // stripped_dark_oak_log
	155: 190, // stripped_pale_oak_log
	156: 196, // stripped_mangrove_log
	157: 19655, // stripped_crimson_stem
	158: 19638, // stripped_warped_stem
	159: 226, // stripped_oak_wood
	160: 229, // stripped_spruce_wood
	161: 232, // stripped_birch_wood
	162: 235, // stripped_jungle_wood
	163: 238, // stripped_acacia_wood
	164: 241, // stripped_cherry_wood
	165: 244, // stripped_dark_oak_wood
	166: 247, // stripped_pale_oak_wood
	167: 250, // stripped_mangrove_wood
	168: 19661, // stripped_crimson_hyphae
	169: 19644, // stripped_warped_hyphae
	170: 199, // stripped_bamboo_block
	171: 202, // oak_wood
	172: 205, // spruce_wood
	173: 208, // birch_wood
	174: 211, // jungle_wood
	175: 214, // acacia_wood
	176: 217, // cherry_wood
	177: 23, // pale_oak_wood
	178: 220, // dark_oak_wood
	179: 223, // mangrove_wood
	180: 19658, // crimson_hyphae
	181: 19641, // warped_hyphae
	182: 279, // oak_leaves
	183: 307, // spruce_leaves
	184: 335, // birch_leaves
	185: 363, // jungle_leaves
	186: 391, // acacia_leaves
	187: 419, // cherry_leaves
	188: 447, // dark_oak_leaves
	189: 475, // pale_oak_leaves
	190: 503, // mangrove_leaves
	191: 531, // azalea_leaves
	192: 559, // flowering_azalea_leaves
	193: 560, // sponge
	194: 561, // wet_sponge
	195: 562, // glass
	196: 23377, // tinted_glass
	197: 565, // lapis_block
	198: 578, // sandstone
	199: 579, // chiseled_sandstone
	200: 580, // cut_sandstone
	201: 2047, // cobweb
	202: 2048, // short_grass
	203: 2049, // fern
	204: 2051, // bush
	205: 25884, // azalea
	206: 25885, // flowering_azalea
	207: 2050, // dead_bush
	208: 27945, // firefly_bush
	209: 2052, // short_dry_grass
	210: 2053, // tall_dry_grass
	211: 2054, // seagrass
	212: 13988, // sea_pickle
	213: 2093, // white_wool
	214: 2094, // orange_wool
	215: 2095, // magenta_wool
	216: 2096, // light_blue_wool
	217: 2097, // yellow_wool
	218: 2098, // lime_wool
	219: 2099, // pink_wool
	220: 2100, // gray_wool
	221: 2101, // light_gray_wool
	222: 2102, // cyan_wool
	223: 2103, // purple_wool
	224: 2104, // blue_wool
	225: 2105, // brown_wool
	226: 2106, // green_wool
	227: 2107, // red_wool
	228: 2108, // black_wool
	229: 2121, // dandelion
	230: 27941, // open_eyeblossom
	231: 27942, // closed_eyeblossom
	232: 2123, // poppy
	233: 2124, // blue_orchid
	234: 2125, // allium
	235: 2126, // azure_bluet
	236: 2127, // red_tulip
	237: 2128, // orange_tulip
	238: 2129, // white_tulip
	239: 2130, // pink_tulip
	240: 2131, // oxeye_daisy
	241: 2132, // cornflower
	242: 2134, // lily_of_the_valley
	243: 2133, // wither_rose
	244: 2122, // torchflower
	245: 13531, // pitcher_plant
	246: 25883, // spore_blossom
	247: 2135, // brown_mushroom
	248: 2136, // red_mushroom
	249: 19664, // crimson_fungus
	250: 19647, // warped_fungus
	251: 19720, // crimson_roots
	252: 19649, // warped_roots
	253: 19650, // nether_sprouts
	254: 19666, // weeping_vines
	255: 19693, // twisting_vines
	256: 5978, // sugar_cane
	257: 13783, // kelp
	258: 25887, // pink_petals
	259: 25903, // wildflowers
	260: 25919, // leaf_litter
	261: 25886, // moss_carpet
	262: 25935, // moss_block
	263: 27777, // pale_moss_carpet
	264: 27939, // pale_hanging_moss
	265: 27776, // pale_moss_block
	266: 25993, // hanging_roots
	267: 25937, // big_dripleaf
	268: 25979, // small_dripleaf
	269: 14000, // bamboo
	270: 12054, // oak_slab
	271: 12060, // spruce_slab
	272: 12066, // birch_slab
	273: 12072, // jungle_slab
	274: 12078, // acacia_slab
	275: 12084, // cherry_slab
	276: 12090, // dark_oak_slab
	277: 12096, // pale_oak_slab
	278: 12102, // mangrove_slab
	279: 12108, // bamboo_slab
	280: 12114, // bamboo_mosaic_slab
	281: 19726, // crimson_slab
	282: 19732, // warped_slab
	283: 12120, // stone_slab
	284: 12126, // smooth_stone_slab
	285: 12132, // sandstone_slab
	286: 12138, // cut_sandstone_slab
	287: 12144, // petrified_oak_slab
	288: 12150, // cobblestone_slab
	289: 12156, // brick_slab
	290: 12162, // stone_brick_slab
	291: 12168, // mud_brick_slab
	292: 12174, // nether_brick_slab
	293: 12180, // quartz_slab
	294: 12186, // red_sandstone_slab
	295: 12192, // cut_red_sandstone_slab
	296: 12198, // purpur_slab
	297: 11598, // prismarine_slab
	298: 11604, // prismarine_brick_slab
	299: 11610, // dark_prismarine_slab
	300: 12203, // smooth_quartz
	301: 12204, // smooth_red_sandstone
	302: 12202, // smooth_sandstone
	303: 12201, // smooth_stone
	304: 2139, // bricks
	305: 2142, // bookshelf
	306: 2206, // chiseled_bookshelf
	307: 27675, // decorated_pot
	308: 2399, // mossy_cobblestone
	309: 2400, // obsidian
	310: 2401, // torch
	311: 13361, // end_rod
	312: 13426, // chorus_plant
	313: 13427, // chorus_flower
	314: 13433, // purpur_block
	315: 13435, // purpur_pillar
	316: 13448, // purpur_stairs
	317: 2919, // spawner
	318: 2927, // creaking_heart
	319: 3019, // chest
	320: 4341, // crafting_table
	321: 4350, // farmland
	322: 4359, // furnace
	323: 4751, // ladder
	324: 4789, // cobblestone_stairs
	325: 5950, // snow
	326: 5958, // ice
	327: 5959, // snow_block
	328: 5960, // cactus
	329: 5976, // cactus_flower
	330: 5977, // clay
	331: 5995, // jukebox
	332: 6027, // oak_fence
	333: 12524, // spruce_fence
	334: 12556, // birch_fence
	335: 12588, // jungle_fence
	336: 12620, // acacia_fence
	337: 12652, // cherry_fence
	338: 12684, // dark_oak_fence
	339: 12716, // pale_oak_fence
	340: 12748, // mangrove_fence
	341: 12780, // bamboo_fence
	342: 19770, // crimson_fence
	343: 19802, // warped_fence
	344: 7054, // pumpkin
	345: 6045, // carved_pumpkin
	346: 6049, // jack_o_lantern
	347: 6028, // netherrack
	348: 6029, // soul_sand
	349: 6030, // soul_soil
	350: 6032, // basalt
	351: 6035, // polished_basalt
	352: 27649, // smooth_basalt
	353: 6037, // soul_torch
	354: 6042, // glowstone
	355: 6786, // infested_stone
	356: 6787, // infested_cobblestone
	357: 6788, // infested_stone_bricks
	358: 6789, // infested_mossy_stone_bricks
	359: 6790, // infested_cracked_stone_bricks
	360: 6791, // infested_chiseled_stone_bricks
	361: 27647, // infested_deepslate
	362: 6780, // stone_bricks
	363: 6781, // mossy_stone_bricks
	364: 6782, // cracked_stone_bricks
	365: 6783, // chiseled_stone_bricks
	366: 6784, // packed_mud
	367: 6785, // mud_bricks
	368: 27232, // deepslate_bricks
	369: 27644, // cracked_deepslate_bricks
	370: 26821, // deepslate_tiles
	371: 27645, // cracked_deepslate_tiles
	372: 27643, // chiseled_deepslate
	373: 27665, // reinforced_deepslate
	374: 6792, // brown_mushroom_block
	375: 6856, // red_mushroom_block
	376: 6920, // mushroom_stem
	377: 7015, // iron_bars
	378: 7019, // chain
	379: 7053, // glass_pane
	380: 7055, // melon
	381: 7111, // vine
	382: 7239, // glow_lichen
	383: 7367, // resin_clump
	384: 7643, // resin_block
	385: 7644, // resin_bricks
	386: 7656, // resin_brick_stairs
	387: 7728, // resin_brick_slab
	388: 7734, // resin_brick_wall
	389: 8055, // chiseled_resin_bricks
	390: 7411, // brick_stairs
	391: 7491, // stone_brick_stairs
	392: 7571, // mud_brick_stairs
	393: 7641, // mycelium
	394: 7642, // lily_pad
	395: 8056, // nether_bricks
	396: 21783, // cracked_nether_bricks
	397: 21782, // chiseled_nether_bricks
	398: 8088, // nether_brick_fence
	399: 8100, // nether_brick_stairs
	400: 23859, // sculk
	401: 23987, // sculk_vein
	402: 23989, // sculk_catalyst
	403: 23997, // sculk_shrieker
	404: 8173, // enchanting_table
	405: 8195, // end_portal_frame
	406: 8199, // end_stone
	407: 13517, // end_stone_bricks
	408: 8200, // dragon_egg
	409: 8226, // sandstone_stairs
	410: 8298, // ender_chest
	411: 8449, // emerald_block
	412: 2949, // oak_stairs
	413: 8461, // spruce_stairs
	414: 8541, // birch_stairs
	415: 8621, // jungle_stairs
	416: 10704, // acacia_stairs
	417: 10784, // cherry_stairs
	418: 10864, // dark_oak_stairs
	419: 10944, // pale_oak_stairs
	420: 11024, // mangrove_stairs
	421: 11104, // bamboo_stairs
	422: 11184, // bamboo_mosaic_stairs
	423: 20006, // crimson_stairs
	424: 20086, // warped_stairs
	425: 8696, // command_block
	426: 8702, // beacon
	427: 8706, // cobblestone_wall
	428: 9030, // mossy_cobblestone_wall
	429: 15218, // brick_wall
	430: 15542, // prismarine_wall
	431: 15866, // red_sandstone_wall
	432: 16190, // mossy_stone_brick_wall
	433: 16514, // granite_wall
	434: 16838, // stone_brick_wall
	435: 17162, // mud_brick_wall
	436: 17486, // nether_brick_wall
	437: 17810, // andesite_wall
	438: 18134, // red_nether_brick_wall
	439: 18458, // sandstone_wall
	440: 18782, // end_stone_brick_wall
	441: 19106, // diorite_wall
	442: 20604, // blackstone_wall
	443: 21461, // polished_blackstone_wall
	444: 21024, // polished_blackstone_brick_wall
	445: 26089, // cobbled_deepslate_wall
	446: 26500, // polished_deepslate_wall
	447: 27322, // deepslate_brick_wall
	448: 26911, // deepslate_tile_wall
	449: 9916, // anvil
	450: 9920, // chipped_anvil
	451: 9924, // damaged_anvil
	452: 10045, // chiseled_quartz_block
	453: 10044, // quartz_block
	454: 21784, // quartz_bricks
	455: 10047, // quartz_pillar
	456: 10060, // quartz_stairs
	457: 10165, // white_terracotta
	458: 10166, // orange_terracotta
	459: 10167, // magenta_terracotta
	460: 10168, // light_blue_terracotta
	461: 10169, // yellow_terracotta
	462: 10170, // lime_terracotta
	463: 10171, // pink_terracotta
	464: 10172, // gray_terracotta
	465: 10173, // light_gray_terracotta
	466: 10174, // cyan_terracotta
	467: 10175, // purple_terracotta
	468: 10176, // blue_terracotta
	469: 10177, // brown_terracotta
	470: 10178, // green_terracotta
	471: 10179, // red_terracotta
	472: 10180, // black_terracotta
	473: 11255, // barrier
	474: 11287, // light
	475: 11615, // hay_block
	476: 11617, // white_carpet
	477: 11618, // orange_carpet
	478: 11619, // magenta_carpet
	479: 11620, // light_blue_carpet
	480: 11621, // yellow_carpet
	481: 11622, // lime_carpet
	482: 11623, // pink_carpet
	483: 11624, // gray_carpet
	484: 11625, // light_gray_carpet
	485: 11626, // cyan_carpet
	486: 11627, // purple_carpet
	487: 11628, // blue_carpet
	488: 11629, // brown_carpet
	489: 11630, // green_carpet
	490: 11631, // red_carpet
	491: 11632, // black_carpet
	492: 11633, // terracotta
	493: 11635, // packed_ice
	494: 13536, // dirt_path
	495: 11637, // sunflower
	496: 11639, // lilac
	497: 11641, // rose_bush
	498: 11643, // peony
	499: 11645, // tall_grass
	500: 11647, // large_fern
	501: 6124, // white_stained_glass
	502: 6125, // orange_stained_glass
	503: 6126, // magenta_stained_glass
	504: 6127, // light_blue_stained_glass
	505: 6128, // yellow_stained_glass
	506: 6129, // lime_stained_glass
	507: 6130, // pink_stained_glass
	508: 6131, // gray_stained_glass
	509: 6132, // light_gray_stained_glass
	510: 6133, // cyan_stained_glass
	511: 6134, // purple_stained_glass
	512: 6135, // blue_stained_glass
	513: 6136, // brown_stained_glass
	514: 6137, // green_stained_glass
	515: 6138, // red_stained_glass
	516: 6139, // black_stained_glass
	517: 10212, // white_stained_glass_pane
	518: 10244, // orange_stained_glass_pane
	519: 10276, // magenta_stained_glass_pane
	520: 10308, // light_blue_stained_glass_pane
	521: 10340, // yellow_stained_glass_pane
	522: 10372, // lime_stained_glass_pane
	523: 10404, // pink_stained_glass_pane
	524: 10436, // gray_stained_glass_pane
	525: 10468, // light_gray_stained_glass_pane
	526: 10500, // cyan_stained_glass_pane
	527: 10532, // purple_stained_glass_pane
	528: 10564, // blue_stained_glass_pane
	529: 10596, // brown_stained_glass_pane
	530: 10628, // green_stained_glass_pane
	531: 10660, // red_stained_glass_pane
	532: 10692, // black_stained_glass_pane
	533: 11352, // prismarine
	534: 11353, // prismarine_bricks
	535: 11354, // dark_prismarine
	536: 11366, // prismarine_stairs
	537: 11446, // prismarine_brick_stairs
	538: 11526, // dark_prismarine_stairs
	539: 11613, // sea_lantern
	540: 11968, // red_sandstone
	541: 11969, // chiseled_red_sandstone
	542: 11970, // cut_red_sandstone
	543: 11982, // red_sandstone_stairs
	544: 13544, // repeating_command_block
	545: 13556, // chain_command_block
	546: 13566, // magma_block
	547: 13567, // nether_wart_block
	548: 19648, // warped_wart_block
	549: 13568, // red_nether_bricks
	550: 13570, // bone_block
	551: 13572, // structure_void
	552: 13589, // shulker_box
	553: 13595, // white_shulker_box
	554: 13601, // orange_shulker_box
	555: 13607, // magenta_shulker_box
	556: 13613, // light_blue_shulker_box
	557: 13619, // yellow_shulker_box
	558: 13625, // lime_shulker_box
	559: 13631, // pink_shulker_box
	560: 13637, // gray_shulker_box
	561: 13643, // light_gray_shulker_box
	562: 13649, // cyan_shulker_box
	563: 13655, // purple_shulker_box
	564: 13661, // blue_shulker_box
	565: 13667, // brown_shulker_box
	566: 13673, // green_shulker_box
	567: 13679, // red_shulker_box
	568: 13685, // black_shulker_box
	569: 13687, // white_glazed_terracotta
	570: 13691, // orange_glazed_terracotta
	571: 13695, // magenta_glazed_terracotta
	572: 13699, // light_blue_glazed_terracotta
	573: 13703, // yellow_glazed_terracotta
	574: 13707, // lime_glazed_terracotta
	575: 13711, // pink_glazed_terracotta
	576: 13715, // gray_glazed_terracotta
	577: 13719, // light_gray_glazed_terracotta
	578: 13723, // cyan_glazed_terracotta
	579: 13727, // purple_glazed_terracotta
	580: 13731, // blue_glazed_terracotta
	581: 13735, // brown_glazed_terracotta
	582: 13739, // green_glazed_terracotta
	583: 13743, // red_glazed_terracotta
	584: 13747, // black_glazed_terracotta
	585: 13751, // white_concrete
	586: 13752, // orange_concrete
	587: 13753, // magenta_concrete
	588: 13754, // light_blue_concrete
	589: 13755, // yellow_concrete
	590: 13756, // lime_concrete
	591: 13757, // pink_concrete
	592: 13758, // gray_concrete
	593: 13759, // light_gray_concrete
	594: 13760, // cyan_concrete
	595: 13761, // purple_concrete
	596: 13762, // blue_concrete
	597: 13763, // brown_concrete
	598: 13764, // green_concrete
	599: 13765, // red_concrete
	600: 13766, // black_concrete
	601: 13767, // white_concrete_powder
	602: 13768, // orange_concrete_powder
	603: 13769, // magenta_concrete_powder
	604: 13770, // light_blue_concrete_powder
	605: 13771, // yellow_concrete_powder
	606: 13772, // lime_concrete_powder
	607: 13773, // pink_concrete_powder
	608: 13774, // gray_concrete_powder
	609: 13775, // light_gray_concrete_powder
	610: 13776, // cyan_concrete_powder
	611: 13777, // purple_concrete_powder
	612: 13778, // blue_concrete_powder
	613: 13779, // brown_concrete_powder
	614: 13780, // green_concrete_powder
	615: 13781, // red_concrete_powder
	616: 13782, // black_concrete_powder
	617: 13811, // turtle_egg
	618: 13823, // sniffer_egg
	619: 13827, // dried_ghast
	620: 13858, // dead_tube_coral_block
	621: 13859, // dead_brain_coral_block
	622: 13860, // dead_bubble_coral_block
	623: 13861, // dead_fire_coral_block
	624: 13862, // dead_horn_coral_block
	625: 13863, // tube_coral_block
	626: 13864, // brain_coral_block
	627: 13865, // bubble_coral_block
	628: 13866, // fire_coral_block
	629: 13867, // horn_coral_block
	630: 13878, // tube_coral
	631: 13880, // brain_coral
	632: 13882, // bubble_coral
	633: 13884, // fire_coral
	634: 13886, // horn_coral
	635: 13870, // dead_brain_coral
	636: 13872, // dead_bubble_coral
	637: 13874, // dead_fire_coral
	638: 13876, // dead_horn_coral
	639: 13868, // dead_tube_coral
	640: 13898, // tube_coral_fan
	641: 13900, // brain_coral_fan
	642: 13902, // bubble_coral_fan
	643: 13904, // fire_coral_fan
	644: 13906, // horn_coral_fan
	645: 13888, // dead_tube_coral_fan
	646: 13890, // dead_brain_coral_fan
	647: 13892, // dead_bubble_coral_fan
	648: 13894, // dead_fire_coral_fan
	649: 13896, // dead_horn_coral_fan
	650: 13996, // blue_ice
	651: 13997, // conduit
	652: 14028, // polished_granite_stairs
	653: 14108, // smooth_red_sandstone_stairs
	654: 14188, // mossy_stone_brick_stairs
	655: 14268, // polished_diorite_stairs
	656: 14348, // mossy_cobblestone_stairs
	657: 14428, // end_stone_brick_stairs
	658: 14508, // stone_stairs
	659: 14588, // smooth_sandstone_stairs
	660: 14668, // smooth_quartz_stairs
	661: 14748, // granite_stairs
	662: 14828, // andesite_stairs
	663: 14908, // red_nether_brick_stairs
	664: 14988, // polished_andesite_stairs
	665: 15068, // diorite_stairs
	666: 26011, // cobbled_deepslate_stairs
	667: 26422, // polished_deepslate_stairs
	668: 27244, // deepslate_brick_stairs
	669: 26833, // deepslate_tile_stairs
	670: 15140, // polished_granite_slab
	671: 15146, // smooth_red_sandstone_slab
	672: 15152, // mossy_stone_brick_slab
	673: 15158, // polished_diorite_slab
	674: 15164, // mossy_cobblestone_slab
	675: 15170, // end_stone_brick_slab
	676: 15176, // smooth_sandstone_slab
	677: 15182, // smooth_quartz_slab
	678: 15188, // granite_slab
	679: 15194, // andesite_slab
	680: 15200, // red_nether_brick_slab
	681: 15206, // polished_andesite_slab
	682: 15212, // diorite_slab
	683: 26083, // cobbled_deepslate_slab
	684: 26494, // polished_deepslate_slab
	685: 27316, // deepslate_brick_slab
	686: 26905, // deepslate_tile_slab
	687: 19458, // scaffolding
	689: 5916, // redstone_torch
	690: 10032, // redstone_block
	691: 6063, // repeater
	692: 9985, // comparator
	693: 2063, // piston
	694: 2041, // sticky_piston
	695: 11253, // slime_block
	696: 20505, // honey_block
	697: 13578, // observer
	698: 10034, // hopper
	699: 567, // dispenser
	700: 10154, // dropper
	701: 19508, // lectern
	702: 20441, // target
	703: 5811, // lever
	704: 25803, // lightning_rod
	705: 10016, // daylight_detector
	706: 23380, // sculk_sensor
	707: 23476, // calibrated_sculk_sensor
	708: 8314, // tripwire_hook
	709: 9929, // trapped_chest
	710: 2141, // tnt
	711: 8202, // redstone_lamp
	712: 582, // note_block
	713: 5935, // stone_button
	714: 21443, // polished_blackstone_button
	715: 9405, // oak_button
	716: 9429, // spruce_button
	717: 9453, // birch_button
	718: 9477, // jungle_button
	719: 9501, // acacia_button
	720: 9525, // cherry_button
	721: 9549, // dark_oak_button
	722: 9573, // pale_oak_button
	723: 9597, // mangrove_button
	724: 9621, // bamboo_button
	725: 20164, // crimson_button
	726: 20188, // warped_button
	727: 5827, // stone_pressure_plate
	728: 21433, // polished_blackstone_pressure_plate
	729: 9952, // light_weighted_pressure_plate
	730: 9968, // heavy_weighted_pressure_plate
	731: 5893, // oak_pressure_plate
	732: 5895, // spruce_pressure_plate
	733: 5897, // birch_pressure_plate
	734: 5899, // jungle_pressure_plate
	735: 5901, // acacia_pressure_plate
	736: 5903, // cherry_pressure_plate
	737: 5905, // dark_oak_pressure_plate
	738: 5907, // pale_oak_pressure_plate
	739: 5909, // mangrove_pressure_plate
	740: 5911, // bamboo_pressure_plate
	741: 19736, // crimson_pressure_plate
	742: 19738, // warped_pressure_plate
	743: 5839, // iron_door
	744: 4697, // oak_door
	745: 12792, // spruce_door
	746: 12856, // birch_door
	747: 12920, // jungle_door
	748: 12984, // acacia_door
	749: 13048, // cherry_door
	750: 13112, // dark_oak_door
	751: 13176, // pale_oak_door
	752: 13240, // mangrove_door
	753: 13304, // bamboo_door
	754: 20214, // crimson_door
	755: 20278, // warped_door
	756: 24723, // copper_door
	757: 24787, // exposed_copper_door
	758: 24915, // weathered_copper_door
	759: 24851, // oxidized_copper_door
	760: 24979, // waxed_copper_door
	761: 25043, // waxed_exposed_copper_door
	762: 25171, // waxed_weathered_copper_door
	763: 25107, // waxed_oxidized_copper_door
	764: 11303, // iron_trapdoor
	765: 6155, // oak_trapdoor
	766: 6219, // spruce_trapdoor
	767: 6283, // birch_trapdoor
	768: 6347, // jungle_trapdoor
	769: 6411, // acacia_trapdoor
	770: 6475, // cherry_trapdoor
	771: 6539, // dark_oak_trapdoor
	772: 6603, // pale_oak_trapdoor
	773: 6667, // mangrove_trapdoor
	774: 6731, // bamboo_trapdoor
	775: 19818, // crimson_trapdoor
	776: 19882, // warped_trapdoor
	777: 25239, // copper_trapdoor
	778: 25303, // exposed_copper_trapdoor
	779: 25431, // weathered_copper_trapdoor
	780: 25367, // oxidized_copper_trapdoor
	781: 25495, // waxed_copper_trapdoor
	782: 25559, // waxed_exposed_copper_trapdoor
	783: 25687, // waxed_weathered_copper_trapdoor
	784: 25623, // waxed_oxidized_copper_trapdoor
	785: 7375, // oak_fence_gate
	786: 12212, // spruce_fence_gate
	787: 12244, // birch_fence_gate
	788: 12276, // jungle_fence_gate
	789: 12308, // acacia_fence_gate
	790: 12340, // cherry_fence_gate
	791: 12372, // dark_oak_fence_gate
	792: 12404, // pale_oak_fence_gate
	793: 12436, // mangrove_fence_gate
	794: 12468, // bamboo_fence_gate
	795: 19938, // crimson_fence_gate
	796: 19970, // warped_fence_gate
	797: 2000, // powered_rail
	798: 2024, // detector_rail
	799: 4759, // rail
	800: 10142, // activator_rail
	847: 20412, // structure_block
	848: 20425, // jigsaw
	849: 20427, // test_block
	850: 20431, // test_instance_block
	911: 4342, // wheat
	943: 4367, // oak_sign
	944: 4399, // spruce_sign
	945: 4431, // birch_sign
	946: 4527, // jungle_sign
	947: 4463, // acacia_sign
	948: 4495, // cherry_sign
	949: 4559, // dark_oak_sign
	950: 4591, // pale_oak_sign
	951: 4623, // mangrove_sign
	952: 4655, // bamboo_sign
	953: 20332, // crimson_sign
	954: 20364, // warped_sign
	955: 4971, // oak_hanging_sign
	956: 5035, // spruce_hanging_sign
	957: 5099, // birch_hanging_sign
	958: 5291, // jungle_hanging_sign
	959: 5163, // acacia_hanging_sign
	960: 5227, // cherry_hanging_sign
	961: 5355, // dark_oak_hanging_sign
	962: 5419, // pale_oak_hanging_sign
	963: 5611, // mangrove_hanging_sign
	964: 5675, // bamboo_hanging_sign
	965: 5483, // crimson_hanging_sign
	966: 5547, // warped_hanging_sign
	982: 13810, // dried_kelp_block
	1040: 6053, // cake
	1041: 1734, // white_bed
	1042: 1750, // orange_bed
	1043: 1766, // magenta_bed
	1044: 1782, // light_blue_bed
	1045: 1798, // yellow_bed
	1046: 1814, // lime_bed
	1047: 1830, // pink_bed
	1048: 1846, // gray_bed
	1049: 1862, // light_gray_bed
	1050: 1878, // cyan_bed
	1051: 1894, // purple_bed
	1052: 1910, // blue_bed
	1053: 1926, // brown_bed
	1054: 1942, // green_bed
	1055: 1958, // red_bed
	1056: 1974, // black_bed
	1058: 27727, // crafter
	1074: 8169, // nether_wart
	1081: 8181, // brewing_stand
	1082: 8182, // cauldron
	1176: 9351, // flower_pot
	1183: 9652, // skeleton_skull
	1184: 9692, // wither_skeleton_skull
	1185: 9772, // player_head
	1186: 9732, // zombie_head
	1187: 9812, // creeper_head
	1188: 9852, // dragon_head
	1189: 9892, // piglin_head
	1214: 11648, // white_banner
	1215: 11664, // orange_banner
	1216: 11680, // magenta_banner
	1217: 11696, // light_blue_banner
	1218: 11712, // yellow_banner
	1219: 11728, // lime_banner
	1220: 11744, // pink_banner
	1221: 11760, // gray_banner
	1222: 11776, // light_gray_banner
	1223: 11792, // cyan_banner
	1224: 11808, // purple_banner
	1225: 11824, // blue_banner
	1226: 11840, // brown_banner
	1227: 11856, // green_banner
	1228: 11872, // red_banner
	1229: 11888, // black_banner
	1276: 19459, // loom
	1288: 20432, // composter
	1289: 19464, // barrel
	1290: 19476, // smoker
	1291: 19484, // blast_furnace
	1292: 19491, // cartography_table
	1293: 19492, // fletching_table
	1294: 19497, // grindstone
	1295: 19521, // smithing_table
	1296: 19522, // stonecutter
	1297: 19527, // bell
	1298: 19561, // lantern
	1299: 19565, // soul_lantern
	1302: 19569, // campfire
	1303: 19601, // soul_campfire
	1304: 19665, // shroomlight
	1306: 20457, // bee_nest
	1307: 20481, // beehive
	1309: 20506, // honeycomb_block
	1310: 20519, // lodestone
	1311: 20509, // crying_obsidian
	1312: 20520, // blackstone
	1313: 20928, // blackstone_slab
	1314: 20532, // blackstone_stairs
	1315: 21345, // gilded_blackstone
	1316: 20931, // polished_blackstone
	1317: 21429, // polished_blackstone_slab
	1318: 21357, // polished_blackstone_stairs
	1319: 20934, // chiseled_polished_blackstone
	1320: 20932, // polished_blackstone_bricks
	1321: 20938, // polished_blackstone_brick_slab
	1322: 20952, // polished_blackstone_brick_stairs
	1323: 20933, // cracked_polished_blackstone_bricks
	1324: 20510, // respawn_anchor
	1325: 21788, // candle
	1326: 21804, // white_candle
	1327: 21820, // orange_candle
	1328: 21836, // magenta_candle
	1329: 21852, // light_blue_candle
	1330: 21868, // yellow_candle
	1331: 21884, // lime_candle
	1332: 21900, // pink_candle
	1333: 21916, // gray_candle
	1334: 21932, // light_gray_candle
	1335: 21948, // cyan_candle
	1336: 21964, // purple_candle
	1337: 21980, // blue_candle
	1338: 21996, // brown_candle
	1339: 22012, // green_candle
	1340: 22028, // red_candle
	1341: 22044, // black_candle
	1342: 22138, // small_amethyst_bud
	1343: 22126, // medium_amethyst_bud
	1344: 22114, // large_amethyst_bud
	1345: 22102, // amethyst_cluster
	1346: 25813, // pointed_dripstone
	1347: 27656, // ochre_froglight
	1348: 27659, // verdant_froglight
	1349: 27662, // pearlescent_froglight
	1350: 27664, // frogspawn
	1395: 25737, // copper_grate
	1396: 25739, // exposed_copper_grate
	1397: 25741, // weathered_copper_grate
	1398: 25743, // oxidized_copper_grate
	1399: 25745, // waxed_copper_grate
	1400: 25747, // waxed_exposed_copper_grate
	1401: 25749, // waxed_weathered_copper_grate
	1402: 25751, // waxed_oxidized_copper_grate
	1403: 25755, // copper_bulb
	1404: 25759, // exposed_copper_bulb
	1405: 25763, // weathered_copper_bulb
	1406: 25767, // oxidized_copper_bulb
	1407: 25771, // waxed_copper_bulb
	1408: 25775, // waxed_exposed_copper_bulb
	1409: 25779, // waxed_weathered_copper_bulb
	1410: 25783, // waxed_oxidized_copper_bulb
	1411: 27736, // trial_spawner
	1414: 27746, // vault
}
